// ═══════════════════════════════════════════════════════════════════
// vocab-level-4.js — Daily French 🥖
// NIVEAU 4 — Les voisins & La vie de quartier + Émotions 🏘️
// Entrées : 67
// ═══════════════════════════════════════════════════════════════════

const VOCAB_LEVEL_4 = [
  {fr:"un voisin",en:"neighbor (male)",phon:"*uh vwa-ZAN*",def:"Personne qui habite à proximité.",ex:"Mon voisin est très gentil.",ex_en:"My neighbour is very kind.",level:4,cat:"social"},
  {fr:"une voisine",en:"neighbor (female)",phon:"*oon vwa-ZEEN*",def:"Femme qui habite à proximité.",ex:"Ma voisine m'aide souvent.",ex_en:"My neighbour often helps me.",level:4,cat:"social"},
  {fr:"le quartier",en:"neighborhood",phon:"*luh kar-TYAY*",def:"Partie d'une ville, zone résidentielle.",ex:"Un quartier très calme.",ex_en:"A very quiet neighbourhood.",level:4,cat:"lieu"},
  {fr:"une rue",en:"a street",phon:"*oon ROO*",def:"Voie publique dans une ville.",ex:"La rue principale du village.",ex_en:"The main street of the village.",level:4,cat:"lieu"},
  {fr:"une impasse",en:"dead end",phon:"*oon om-PASS*",def:"Rue sans issue.",ex:"J'habite dans une impasse.",ex_en:"I live in a dead end.",level:4,cat:"lieu"},
  {fr:"le bruit",en:"noise",phon:"*luh BREE*",def:"Son désagréable ou fort.",ex:"Il y a trop de bruit.",ex_en:"There is too much noise.",level:4,cat:"sensation"},
  {fr:"le calme",en:"quiet / calm",phon:"*luh KALM*",def:"Absence de bruit, tranquillité.",def_en:"Absence of noise, tranquillity.",ex:"Le calme du quartier.",ex_en:"The quiet of the neighbourhood.",level:4,cat:"sensation"},
  {fr:"emprunter",en:"to borrow",phon:"*om-PRON-tay*",def:"Utiliser temporairement quelque chose.",ex:"Je peux vous emprunter une échelle ?",ex_en:"Can I borrow a ladder from you?",level:4,cat:"verbe"},
  {fr:"prêter",en:"to lend",phon:"*PRAY-tay*",def:"Donner temporairement quelque chose.",def_en:"To temporarily give something.",ex:"Je vous prête mon livre.",ex_en:"I'll lend you my book.",level:4,cat:"verbe"},
  {fr:"désolé",en:"sorry (man)",phon:"*day-zo-LAY*",def:"Exprimer des excuses.",ex:"Je suis désolé du dérangement.",ex_en:"I'm sorry for the disturbance.",level:4,cat:"politesse"},
  {fr:"triste",en:"sad",phon:"*TREEST*",def:"Qui ressent de la peine",ex:"Je suis triste aujourd'hui.",level:4,cat:"sentiment"},
  {fr:"déçu",en:"disappointed",phon:"*day-SOO*",def:"Qui a subi une déception",ex:"Je suis déçu par les résultats.",level:4,cat:"sentiment"},
  {fr:"ennuyé",en:"bored / annoyed",phon:"*on-nwee-YAY*",def:"Qui s'ennuie ou qui est contrarié",ex:"Je suis ennuyé par cette situation.",level:4,cat:"sentiment"},
  {fr:"gêné",en:"embarrassed / uncomfortable",phon:"*zhay-NAY*",def:"Qui se sent mal à l'aise",ex:"Je suis gêné de demander.",level:4,cat:"sentiment"},
  {fr:"en colère",en:"angry",phon:"*on ko-LAIR*",def:"Qui ressent de la rage",ex:"Je suis en colère contre lui.",level:4,cat:"sentiment"},
  {fr:"fâché",en:"mad / upset",phon:"*fa-SHAY*",def:"Qui est en conflit",ex:"Ils sont fâchés depuis hier.",level:4,cat:"sentiment"},
  {fr:"jaloux",en:"jealous (male)",phon:"*zha-LOO*",def:"Qui envie les autres",ex:"Il est jaloux de son frère.",level:4,cat:"sentiment"},
  {fr:"jalouse",en:"jealous (female)",phon:"*zha-LOOZ*",def:"Qui envie les autres",ex:"Elle est jalouse de sa sœur.",level:4,cat:"sentiment"},
  {fr:"inquiet",en:"worried (male)",phon:"*on-kee-AY*",def:"Qui a de l'anxiété",ex:"Je suis inquiet pour ma fille.",level:4,cat:"sentiment"},
  {fr:"inquiète",en:"worried (female)",phon:"*on-kee-ET*",def:"Qui a de l'anxiété",ex:"Elle est inquiète pour son mari.",level:4,cat:"sentiment"},
  {fr:"stressé",en:"stressed (male)",phon:"*stres-SAY*",def:"Qui subit de la pression",ex:"Je suis stressé par le travail.",level:4,cat:"sentiment"},
  {fr:"stressée",en:"stressed (female)",phon:"*stres-SAY*",def:"Qui subit de la pression",ex:"Elle est stressée par les examens.",level:4,cat:"sentiment"},
  {fr:"frustré",en:"frustrated (male)",phon:"*froos-TRAY*",def:"Qui ressent de la frustration",ex:"Je suis frustré par ce retard.",level:4,cat:"sentiment"},
  {fr:"frustrée",en:"frustrated (female)",phon:"*froos-TRAY*",def:"Qui ressent de la frustration",ex:"Elle est frustrée par la bureaucratie.",level:4,cat:"sentiment"},
  {fr:"agacé",en:"irritated (male)",phon:"*a-ga-SAY*",def:"Qui est exaspéré",ex:"Je suis agacé par le bruit.",level:4,cat:"sentiment"},
  {fr:"agacée",en:"irritated (female)",phon:"*a-ga-SAY*",def:"Qui est exaspérée",ex:"Elle est agacée par les interruptions.",level:4,cat:"sentiment"},
  {fr:"vexé",en:"offended (male)",phon:"*vek-SAY*",def:"Qui a été blessé dans son amour-propre",ex:"Il est vexé par ce que tu as dit.",level:4,cat:"sentiment"},
  {fr:"vexée",en:"offended (female)",phon:"*vek-SAY*",def:"Qui a été blessée dans son amour-propre",ex:"Elle est vexée par le refus.",level:4,cat:"sentiment"},
  {fr:"honteux",en:"ashamed (male)",phon:"*on-TOH*",def:"Qui ressent de la honte",ex:"Je suis honteux de mon comportement.",level:4,cat:"sentiment"},
  {fr:"honteuse",en:"ashamed (female)",phon:"*on-TOHZ*",def:"Qui ressent de la honte",ex:"Elle est honteuse de son erreur.",level:4,cat:"sentiment"},
  {fr:"méfiant",en:"suspicious / wary (male)",phon:"*may-FYAN*",def:"Qui se méfie",ex:"Je suis méfiant des étrangers.",level:4,cat:"sentiment"},
  {fr:"méfiante",en:"suspicious / wary (female)",phon:"*may-FYANT*",def:"Qui se méfie",ex:"Elle est méfiante des promesses.",level:4,cat:"sentiment"},
  {fr:"désespéré",en:"desperate (male)",phon:"*day-zes-puh-RAY*",def:"Sans espoir",ex:"Je suis désespéré de cette situation.",level:4,cat:"sentiment"},
  {fr:"désespérée",en:"desperate (female)",phon:"*day-zes-puh-RAY*",def:"Sans espoir",ex:"Elle est désespérée de trouver un logement.",level:4,cat:"sentiment"},
  {fr:"résigné",en:"resigned (male)",phon:"*ray-zee-NAY*",def:"Qui accepte sans espoir",ex:"Je suis résigné à attendre.",level:4,cat:"sentiment"},
  {fr:"résignée",en:"resigned (female)",phon:"*ray-zee-NAY*",def:"Qui accepte sans espoir",ex:"Elle est résignée à son sort.",level:4,cat:"sentiment"},
  {fr:"indigné",en:"outraged (male)",phon:"*on-dee-NYAY*",def:"Qui réprouve fortement",ex:"Je suis indigné par cette injustice.",level:4,cat:"sentiment"},
  {fr:"indignée",en:"outraged (female)",phon:"*on-dee-NYAY*",def:"Qui réprouve fortement",ex:"Elle est indignée par la corruption.",level:4,cat:"sentiment"},
  {fr:"révolté",en:"revolted / rebellious (male)",phon:"*ray-vol-TAY*",def:"Qui refuse d'accepter",ex:"Je suis révolté par cette décision.",level:4,cat:"sentiment"},
  {fr:"révoltée",en:"revolted / rebellious (female)",phon:"*ray-vol-TAY*",def:"Qui refuse d'accepter",ex:"Elle est révoltée par l'inégalité.",level:4,cat:"sentiment"},
  {fr:"écœuré",en:"disgusted / sickened (male)",phon:"*ay-kur-RAY*",def:"Qui ressent du dégoût",ex:"Je suis écœuré par ce scandale.",level:4,cat:"sentiment"},
  {fr:"écœurée",en:"disgusted / sickened (female)",phon:"*ay-kur-RAY*",def:"Qui ressent du dégoût",ex:"Elle est écœurée par la violence.",level:4,cat:"sentiment"},
  {fr:"atterré",en:"appalled / dismayed (male)",phon:"*a-tair-RAY*",def:"Profondément choqué",ex:"Je suis atterré par les nouvelles.",level:4,cat:"sentiment"},
  {fr:"atterrée",en:"appalled / dismayed (female)",phon:"*a-tair-RAY*",def:"Profondément choquée",ex:"Elle est atterrée par le bilan.",level:4,cat:"sentiment"},
  {fr:"accablé",en:"overwhelmed / crushed (male)",phon:"*a-ka-BLAY*",def:"Qui subit trop",ex:"Je suis accablé de travail.",level:4,cat:"sentiment"},
  {fr:"accablée",en:"overwhelmed / crushed (female)",phon:"*a-ka-BLAY*",def:"Qui subit trop",ex:"Elle est accablée de chagrin.",level:4,cat:"sentiment"},
  {fr:"abattu",en:"dejected / downcast (male)",phon:"*a-ba-TOO*",def:"Moralement abattu",ex:"Il est abattu par l'échec.",level:4,cat:"sentiment"},
  {fr:"abattue",en:"dejected / downcast (female)",phon:"*a-ba-TOO*",def:"Moralement abattue",ex:"Elle est abattue par la nouvelle.",level:4,cat:"sentiment"},
  {fr:"morose",en:"gloomy / morose",phon:"*mo-ROHZ*",def:"D'humeur sombre",ex:"Il est morose depuis la mort de son chien.",level:4,cat:"sentiment"},
  {fr:"maussade",en:"sullen / glum",phon:"*moh-SAHD*",def:"De mauvaise humeur",ex:"Elle est maussade ce matin.",level:4,cat:"sentiment"},
  {fr:"grognon",en:"grumpy",phon:"*gron-YON*",def:"Qui râle souvent",ex:"Mon voisin est grognon.",level:4,cat:"sentiment"},
  {fr:"râleur",en:"complainer (male)",phon:"*ra-LUR*",def:"Qui se plaint beaucoup",ex:"C'est un râleur professionnel.",level:4,cat:"sentiment"},
  {fr:"râleuse",en:"complainer (female)",phon:"*ra-LOZ*",def:"Qui se plaint beaucoup",ex:"Elle est râleuse mais gentille.",level:4,cat:"sentiment"},
  {fr:"pessimiste",en:"pessimistic",phon:"*pay-see-MEEST*",def:"Qui voit le mal",ex:"Je suis pessimiste pour l'avenir.",level:4,cat:"sentiment"},
  {fr:"optimiste",en:"optimistic",phon:"*op-tee-MEEST*",def:"Qui voit le bien",ex:"Elle reste optimiste malgré tout.",level:4,cat:"sentiment"},
  {fr:"nerveux",en:"nervous (male)",phon:"*nair-VOO*",def:"Qui a les nerfs à vif",ex:"Je suis nerveux avant l'examen.",level:4,cat:"sentiment"},
  {fr:"nerveuse",en:"nervous (female)",phon:"*nair-VOOZ*",def:"Qui a les nerfs à vif",ex:"Elle est nerveuse en avion.",level:4,cat:"sentiment"},
  {fr:"paniqué",en:"panicked (male)",phon:"*pa-nee-KAY*",def:"Qui a perdu le contrôle",ex:"Je suis paniqué, j'ai perdu mes clés.",level:4,cat:"sentiment"},
  {fr:"paniquée",en:"panicked (female)",phon:"*pa-nee-KAY*",def:"Qui a perdu le contrôle",ex:"Elle est paniquée par l'incendie.",level:4,cat:"sentiment"},
  {fr:"horrifié",en:"horrified (male)",phon:"*o-ree-fee-AY*",def:"Profondément choqué",ex:"Je suis horrifié par l'attentat.",level:4,cat:"sentiment"},
  {fr:"horrifiée",en:"horrified (female)",phon:"*o-ree-fee-AY*",def:"Profondément choquée",ex:"Elle est horrifiée par les images.",level:4,cat:"sentiment"},
  {fr:"traumatisé",en:"traumatized (male)",phon:"*troo-ma-tee-ZAY*",def:"Marqué par un choc",ex:"Il est traumatisé par l'accident.",level:4,cat:"sentiment"},
  {fr:"traumatisée",en:"traumatized (female)",phon:"*troo-ma-tee-ZAY*",def:"Marquée par un choc",ex:"Elle est traumatisée par la guerre.",level:4,cat:"sentiment"},
  {fr:"soulagé",en:"relieved (male)",phon:"*soo-la-ZHAY*",def:"Qui ressent un allègement",ex:"Je suis soulagé que ce soit fini.",level:4,cat:"sentiment"},
  {fr:"soulagée",en:"relieved (female)",phon:"*soo-la-ZHAY*",def:"Qui ressent un allègement",ex:"Elle est soulagée d'être rentrée.",level:4,cat:"sentiment"},
  {fr:"reconnaissant",en:"grateful (male)",phon:"*ruh-kon-nay-SAN*",def:"Qui a de la gratitude",ex:"Je suis reconnaissant de votre aide.",level:4,cat:"sentiment"},
  {fr:"reconnaissante",en:"grateful (female)",phon:"*ruh-kon-nay-SANT*",def:"Qui a de la gratitude",ex:"Elle est reconnaissante de votre soutien.",level:4,cat:"sentiment"}
];

if (typeof window !== 'undefined') {
  window.VOCAB_LEVEL_4 = VOCAB_LEVEL_4;
}
