// ═══════════════════════════════════════════════════════════════════
// EMERGENCY-DATA.JS — Daily French 🥖
// Phrases d'urgence et de survie quotidien par situation réelle
// ═══════════════════════════════════════════════════════════════════

const EMERGENCY_CATEGORIES = [
  {
    id: 'pharmacie',
    icon: '💊',
    title: 'Pharmacie',
    titleEn: 'Pharmacy',
    color: '#059669',
    desc: 'Maux du quotidien, médicaments, allergies',
    descEn: 'Everyday ailments, medication, allergies',
    phrases: [
      { fr: "J'ai mal à la tête", phon: "Jhay mal ah lah TET", en: "I have a headache", context: "Pour demander un médicament contre la douleur" },
      { fr: "J'ai mal au ventre", phon: "Jhay mal oh VAHN-truh", en: "I have a stomach ache", context: "Maux de ventre, indigestion" },
      { fr: "J'ai de la fièvre", phon: "Jhay duh lah fee-EH-vruh", en: "I have a fever", context: "Quand vous avez de la température" },
      { fr: "J'ai attrapé un rhume", phon: "Jhay ah-trah-PAY uhn room", en: "I caught a cold", context: "Rhume, nez bouché, toux" },
      { fr: "Avez-vous un médicament sans ordonnance ?", phon: "Ah-vay voo uhn may-dee-kah-MAHN sahn or-don-NAHNS", en: "Do you have any over-the-counter medicine?", context: "Médicament sans prescription médicale" },
      { fr: "Je suis allergique à la pénicilline", phon: "Juh swee al-lair-ZHEEK ah lah pay-nee-see-LEEN", en: "I'm allergic to penicillin", context: "ALLERGIE IMPORTANTE — à dire systématiquement" },
      { fr: "Je suis allergique aux antibiotiques", phon: "Juh swee al-lair-ZHEEK oh zahn-tee-bee-oh-TEEK", en: "I'm allergic to antibiotics", context: "Si vous avez une allergie aux antibiotiques" },
      { fr: "Ça fait mal ici", phon: "Sah fay mal ee-SEE", en: "It hurts here", context: "Montrez où vous avez mal" },
      { fr: "J'ai une éruption cutanée", phon: "Jhay oon ay-roop-see-oh kyoo-tah-NAY", en: "I have a skin rash", context: "Rougeurs, boutons, démangeaisons" },
      { fr: "J'ai une entorse à la cheville", phon: "Jhay ohn ahn-TORSE ah lah shuh-VEEL", en: "I have a sprained ankle", context: "Cheville foulée, enflée" },
      { fr: "Il m'a fallu des points de suture", phon: "Eel mah fah-LEW day PWAHN duh soo-TEWR", en: "I needed stitches", context: "Après une blessure profonde" },
      { fr: "J'ai besoin d'un pansement", phon: "Jhay buh-ZWAHN duhn pahn-SAH-mahn", en: "I need a bandage", context: "Coupe, égratignure" },
      { fr: "C'est pour un enfant de 9 ans", phon: "Say poor uhn ahn-FAHN duh N UHF ahn", en: "It's for a 9-year-old child", context: "Pour demander un médicament adapté" },
      { fr: "Quelle est la dose recommandée ?", phon: "Kel eh lah DOHZ ruh-koh-mahn-DAY", en: "What is the recommended dose?", context: "Posologie du médicament" },
      { fr: "Ça soulage la douleur ?", phon: "Sah soo-LAHNZH lah doo-LEWR", en: "Does this relieve the pain?", context: "Vérifier l'effet du médicament" }
    ]
  },
  {
    id: 'medecin',
    icon: '🩺',
    title: 'Médecin / Urgences',
    titleEn: 'Doctor / Emergency',
    color: '#DC2626',
    desc: 'Rendez-vous, symptômes, questions médicales',
    descEn: 'Appointments, symptoms, medical questions',
    phrases: [
      { fr: "Je voudrais prendre rendez-vous avec le docteur", phon: "Juh voo-DRAY PRAHN-druh rahn-day-VOO ah-VECK luh dok-TORE", en: "I'd like to make an appointment with the doctor", context: "Premier contact avec le cabinet médical" },
      { fr: "C'est une urgence", phon: "Say toon oor-ZHAHNZH", en: "It's an emergency", context: "Si vous devez voir un médecin rapidement" },
      { fr: "Je ne me sens pas bien", phon: "Juh nuh muh sahn pah byan", en: "I'm not feeling well", context: "État général de malaise" },
      { fr: "J'ai des nausées", phon: "Jhay day noh-ZAY", en: "I'm feeling nauseous", context: "Envie de vomir" },
      { fr: "J'ai des vertiges", phon: "Jhay day vair-TEEZH", en: "I'm dizzy", context: "Tête qui tourne, équilibre" },
      { fr: "Je tousse beaucoup", phon: "Juh TOOSS boh-KOO", en: "I'm coughing a lot", context: "Toux persistante" },
      { fr: "J'ai du mal à respirer", phon: "Jhay doo mal ah res-phee-RAY", en: "I'm having trouble breathing", context: "ESSENTIEL — difficulté respiratoire" },
      { fr: "J'ai été en contact avec quelqu'un qui a la grippe", phon: "Jhay ay-TAY ahn kohn-TAHCT ah-VECK kel-KUHN kee ah lah greep", en: "I've been in contact with someone who has the flu", context: "Pour le médecin, contexte médical" },
      { fr: "J'ai des antécédents cardiaques", phon: "Jhay day zahn-tay-say-DON car-dee-AHK", en: "I have a heart condition", context: "Historique médical important" },
      { fr: "Je suis diabétique", phon: "Juh swee dee-ah-bay-TEEK", en: "I'm diabetic", context: "À mentionner systématiquement" },
      { fr: "Je prends ces médicaments en permanence", phon: "Juh PRON say may-dee-kah-MAHN ahn pair-mah-NAHNS", context: "Montrez vos médicaments habituels" },
      { fr: "Je suis enceinte", phon: "Juh swee zahn-SANT", en: "I'm pregnant", context: "Si vous êtes enceinte" },
      { fr: "Ça dure depuis combien de temps ?", phon: "Sah DOOR duh-PEE koh-BYAN duh tahn", en: "How long has this been going on?", context: "Question que le médecin posera" },
      { fr: "Où se trouve le centre hospitalier le plus proche ?", phon: "Oo suh troov luh SAHN-tree o-spee-tah-LYAY luh ploo PROHSH", en: "Where is the nearest hospital?", context: "En cas d'urgence" },
      { fr: "Pouvez-vous faire une ordonnance ?", phon: "Poo-vay voo fair oon or-don-NAHNS", en: "Can you write a prescription?", context: "Pour obtenir une prescription" }
    ]
  },
  {
    id: 'admin',
    icon: '📋',
    title: 'Administration / Mairie',
    titleEn: 'Administration / Town Hall',
    color: '#4A5568',
    desc: 'Papiers, inscription, démarches officielles',
    descEn: 'Paperwork, registration, official procedures',
    phrases: [
      { fr: "Je voudrais changer mon adresse", phon: "Juh voo-DRAY shahn-ZHAY mohn ah-DRESS", en: "I'd like to change my address", context: "Changement d'adresse à la mairie" },
      { fr: "Je voudrais m'inscrire sur les listes électorales", phon: "Juh voo-DRAY mahs-KREER soor lay LEEST ay-lek-toh-RAL", en: "I'd like to register to vote", context: "Inscription électorale" },
      { fr: "Je voudrais un certificat de résidence", phon: "Juh voo-DRAY uhn sair-tee-fee-KAH duh ray-zee-DAHNS", en: "I'd like a certificate of residence", context: "Justificatif de domicile" },
      { fr: "Quels sont les documents nécessaires ?", phon: "Kel sohn lay dok-oo-MAHN nay-say-SAIR", en: "What documents are needed?", context: "Demander la liste des papiers" },
      { fr: "Puis-je prendre rendez-vous en ligne ?", phon: "Pwee zhuh PRON-druh rahn-day-VOO ahn LEEN", en: "Can I make an appointment online?", context: "RDV via internet" },
      { fr: "Comment faire une réclamation ?", phon: "Koh-MAHN fair oon ray-klah-mah-SYOHN", en: "How do I make a complaint?", context: "Si vous avez un problème" },
      { fr: "Je n'ai pas encore reçu ma carte d'identité", phon: "Juh nay pah zahn-KOR ruh-SEW mah kart dee-dahn-tee-TAY", en: "I haven't received my ID card yet", context: "Suivi de demande" },
      { fr: "Où puis-je déposer mon dossier ?", phon: "Oo pwee zhuh day-poh-ZAY mohn doh-SYAY", en: "Where can I submit my file?", context: "Lieu de dépôt" },
      { fr: "Le guichet est ouvert jusqu'à quelle heure ?", phon: "Luh gee-SHAY ay too-VAY zhoo-SKAH kel UR", en: "What time does the counter close?", context: "Horaires d'ouverture" },
      { fr: "Y a-t-il une file d'attente ?", phon: "Ee ah-TEEL oon FEEL dah-TAHNT", en: "Is there a queue?", context: "Attente au guichet" },
      { fr: "Je voudrais déclarer un changement de situation", phon: "Juh voo-DRAY day-klah-RAY uhn shahn-ZHAH-MAN duh see-twa-SYOHN", en: "I'd like to report a change of situation", context: "Mariage, naissance, divorce" },
      { fr: "Pouvez-vous m'orienter vers le bon service ?", phon: "Poo-vay voo maw-ree-ahn-TAY vair luh bohn sair-VEES", en: "Can you direct me to the right department?", context: "Quand vous ne savez pas où aller" },
      { fr: "Je suis étranger, quel est mon statut ?", phon: "Juh swee zay-TRAHN-ZHAY, kel ay mohn stah-TEW", en: "I'm a foreigner, what is my status?", context: "Questions d'immigration" },
      { fr: "Mon dossier est incomplet, que me manque-t-il ?", phon: "Mohn doh-SYAY ay zan-kohm-PLET, kuh muh MAHNK-teel", en: "My file is incomplete, what am I missing?", context: "Dossier incomplet" },
      { fr: "Puis-je avoir un reçu ?", phon: "Pwee zhuh ah-VWAIR uhn ruh-SEW", en: "Can I have a receipt?", context: "Preuve de dépôt" }
    ]
  },
  {
    id: 'logement',
    icon: '🏠',
    title: 'Logement / Immobilier',
    titleEn: 'Housing / Real Estate',
    color: '#7C3AED',
    desc: 'Propriétaire, location, voisinage, travaux',
    descEn: 'Landlord, renting, neighbors, repairs',
    phrases: [
      { fr: "Le robinet fuit", phon: "Luh rob-ee-NAY FWEE", en: "The tap is leaking", context: "Fuite d'eau" },
      { fr: "Le chauffage ne marche pas", phon: "Luh shoh-FAHZH nuh MARSH pah", en: "The heating isn't working", context: "Panne de chauffage" },
      { fr: "La chasse d'eau est cassée", phon: "Lah SHAHS doh ay kah-SAY", en: "The toilet flush is broken", context: "WC défectueux" },
      { fr: "Il y a une coupure d'électricité", phon: "Eel yah oon koo-POOR day-lek-tree-see-TEE-TAY", en: "There's a power cut", context: "Panne électrique" },
      { fr: "Le courant est coupé, c'est un problème général ?", phon: "Luh koo-RAHN ay koo-PAY, say uhn prob-LEM zhay-nay-RAL", en: "The power is out, is it a general problem?", context: "Vérifier si c'est local ou général" },
      { fr: "Le voisin fait du bruit", phon: "Luh vwah-ZAN fay doo BWEE", en: "The neighbour is making noise", context: "Troubles du voisinage" },
      { fr: "Je voudrais signaler un dégât des eaux", phon: "Juh voo-DRAY seen-yahl-LAY uhn day-GAH day ZOH", en: "I'd like to report water damage", context: "Infiltration, inondation" },
      { fr: "Quand est prévue la prochaine intervention ?", phon: "Kahn ay pray-VW lah proh-SHENN an-tair-vahn-SYOHN", en: "When is the next repair scheduled?", context: "Suivi de réparation" },
      { fr: "Je voudrais résilier mon bail", phon: "Juh voo-DRAY ray-zee-LYAY mohn bahy", en: "I'd like to terminate my lease", context: "Quitter un logement loué" },
      { fr: "Le propriétaire ne répond pas", phon: "Luh pro-pree-ay-TAIR nuh ray-PON pah", en: "The landlord isn't responding", context: "Propriétaire injoignable" },
      { fr: "La fenêtre ne ferme plus", phon: "Lah fahn-TRUH nuh FERM ploo", en: "The window won't close", context: "Problème de fenêtre" },
      { fr: "Il y a des moisissures sur les murs", phon: "Eel yah day mwah-zee-SUR soor lay mewr", en: "There's mould on the walls", context: "Humidité, moisissure" },
      { fr: "Pouvez-vous envoyer un artisan ?", phon: "Poo-vay voo ahn-vwah-YAY uhn ar-tee-ZAN", en: "Can you send a tradesman?", context: "Demande de réparation" },
      { fr: "Je voudrais souscrire une assurance habitation", phon: "Juh voo-DRAY soo-skruh-REWR ohn ahs-syu-RAHNS ah-bee-tah-SYOHN", en: "I'd like to take out home insurance", context: "Assurance logement" },
      { fr: "Le loyer sera payé en retard ce mois-ci", phon: "Luh lwah-YAY sair-rah pay-YAY ahn ruh-TAR suh mwah-SEE", en: "The rent will be paid late this month", context: "Retard de paiement" }
    ]
  },
  {
    id: 'courses',
    icon: '🛒',
    title: 'Courses / Magasins',
    titleEn: 'Shopping / Stores',
    color: '#F59E0B',
    desc: 'Supermarché, boulangerie, réclamations',
    descEn: 'Supermarket, bakery, complaints',
    phrases: [
      { fr: "Où se trouve [le rayon pain] ?", phon: "Oo suh troov [luh ray-YOHN pan]", en: "Where is [the bread aisle]?", context: "Demander un rayon au supermarché" },
      { fr: "Avez-vous ça en plus grand / plus petit ?", phon: "Ah-vay voo sahn ploo GRAN / ploo puh-TEE", en: "Do you have this in a larger / smaller size?", context: "Taille, pointure, format" },
      { fr: "Je cherche [les produits bio]", phon: "Juh SHARE-shay [lay pro-dwee bee-OH]", en: "I'm looking for [organic products]", context: "Recherche de produits" },
      { fr: "À quelle heure fermez-vous ce soir ?", phon: "Ah kel UR fair-MAY voo suh SWAR", en: "What time do you close tonight?", context: "Horaires de fermeture" },
      { fr: "Le produit est périmé", phon: "Luh pro-dwee ay pay-ree-MAY", en: "The product is expired", context: "Date de péremption dépassée" },
      { fr: "Je voudrais échanger cet article", phon: "Juh voo-DRAY ay-shahn-ZHAY say tar-TEE-kluh", en: "I'd like to exchange this item", context: "Retour ou échange" },
      { fr: "J'ai oublié mon sac réutilisable", phon: "Jhay oo-blee-AY mohn sak ray-oo-tee-lee-ZAH-bluh", en: "I forgot my reusable bag", context: "Pas de sac pour les courses" },
      { fr: "Acceptez-vous les chèques ?", phon: "Ak-sep-TAY voo lay SHEK", en: "Do you accept cheques?", context: "Moyen de paiement" },
      { fr: "Puis-je payer en plusieurs fois ?", phon: "Pwee zhuh pay-YAY ahn plew-ZYUR fwah", en: "Can I pay in instalments?", context: "Paiement fractionné" },
      { fr: "C'est en promotion ?", phon: "Say ahn pro-moh-SYOHN", en: "Is it on sale?", context: "Demander une réduction" },
      { fr: "Auriez-vous ça en magasin ?", phon: "Oh-ree-AY voo sahn ahn mag-ah-ZAN", en: "Would you have this in stock?", context: "Produit indisponible" },
      { fr: "Je voudrais un remboursement", phon: "Juh voo-DRAY uhn rahn-boor-SAH-MAN", en: "I'd like a refund", context: "Demander un remboursement" },
      { fr: "Le prix affiché ne correspond pas", phon: "Luh PREE ah-fee-SHAY nuh kor-res-PON pah", en: "The displayed price doesn't match", context: "Erreur de prix" },
      { fr: "Pouvez-vous me faire un sac cadeau ?", phon: "Poo-vay voo muh fair uhn sak kah-DOH", en: "Can you gift-wrap this?", context: "Pour un cadeau" },
      { fr: "Je prends celui-ci / celle-là", phon: "Juh PRON suh-lwee-SEE / sell-LAH", en: "I'll take this one", context: "Choisir un article" }
    ]
  },
  {
    id: 'transports',
    icon: '🚆',
    title: 'Transports / Gare',
    titleEn: 'Transport / Train Station',
    color: '#2563EB',
    desc: 'Train, bus, taxi, retard, itinéraire',
    descEn: 'Train, bus, taxi, delays, directions',
    phrases: [
      { fr: "Un aller-simple pour [Paris], s'il vous plaît", phon: "Uhn ah-lay-SAN-pl poor [pah-REE], seel voo PLEH", en: "A one-way ticket to [Paris], please", context: "Achat de billet simple" },
      { fr: "Un aller-retour pour [Lyon], s'il vous plaît", phon: "Uhn ah-lay ruh-TOOR poor [lee-OHN], seel voo PLEH", en: "A return ticket to [Lyon], please", context: "Achat de billet aller-retour" },
      { fr: "Le train est-il à l'heure ?", phon: "Luh tran ay-TEEL ah LUR", en: "Is the train on time?", context: "Vérifier les horaires" },
      { fr: "Quel est le prochain train pour [Nantes] ?", phon: "Kel ay luh proh-SHAN tran poor [NAHNT]", en: "What is the next train to [Nantes]?", context: "Prochains départs" },
      { fr: "À quelle voie part le train ?", phon: "Ah kel VWAHR par luh tran", en: "Which platform does the train leave from?", context: "Chercher son quai" },
      { fr: "Le train est en retard", phon: "Luh tran ay tahn ruh-TAR", en: "The train is delayed", context: "Annonce de retard" },
      { fr: "Le train est supprimé", phon: "Luh tran ay soo-pree-MAY", en: "The train has been cancelled", context: "Annonce de suppression" },
      { fr: "Puis-je bénéficier d'un billet de substitution ?", phon: "Pwee zhuh bay-nay-fee-SYAY duhn bee-YAY duh soob-stee-tew-SYOHN", en: "Can I get a replacement ticket?", context: "Train supprimé" },
      { fr: "Où est la consigne à bagages ?", phon: "Oo ay lah kohn-SEEN yah bah-GAHZH", en: "Where is the luggage storage?", context: "Consigne" },
      { fr: "Le bus [15] s'arrête où ?", phon: "Luh bews [kanz] sah-RET oo", en: "Where does bus [15] stop?", context: "Arrêt de bus" },
      { fr: "Je voudrais prendre un taxi", phon: "Juh voo-DRAY PRON-druh uhn tak-SEE", en: "I'd like to take a taxi", context: "Appeler un taxi" },
      { fr: "Pouvez-vous m'appeler un taxi ?", phon: "Poo-vay voo mah-play uhn tak-SEE", en: "Can you call me a taxi?", context: "Demande à un commerçant" },
      { fr: "Je suis descendu à la mauvaise gare", phon: "Juh swee day-sahn-DEW ah lah moh-VAHZ gar", en: "I got off at the wrong station", context: "Erreur de gare" },
      { fr: "Mon train est supprimé, que dois-je faire ?", phon: "Mohn tran ay soo-pree-MAY, kuh dwahzh fair", en: "My train is cancelled, what should I do?", context: "Demander une solution" },
      { fr: "Y a-t-il un bus de remplacement ?", phon: "Ee ah-TEEL uhn bews duh rahn-plahs-MAHN", en: "Is there a replacement bus?", context: "Service de substitution" }
    ]
  },
  {
    id: 'banque',
    icon: '🏦',
    title: 'Banque / Poste',
    titleEn: 'Bank / Post Office',
    color: '#0891B2',
    desc: 'Compte, virement, chèque, colis',
    descEn: 'Account, transfer, cheque, parcels',
    phrases: [
      { fr: "Je voudrais ouvrir un compte bancaire", phon: "Juh voo-DRAY oo-vree-R uhn kohnt bahn-KAIR", en: "I'd like to open a bank account", context: "Ouverture de compte" },
      { fr: "Je voudrais fermer mon compte", phon: "Juh voo-DRAY fair-MAY mohn kohnt", en: "I'd like to close my account", context: "Fermeture de compte" },
      { fr: "Je voudrais faire un virement", phon: "Juh voo-DRAY fair uhn veer-MAHN", en: "I'd like to make a transfer", context: "Virement bancaire" },
      { fr: "Je voudrais changer mon code PIN", phon: "Juh voo-DRAY shahn-ZHAY mohn kohd pee-ehn", en: "I'd like to change my PIN", context: "Code de carte" },
      { fr: "Ma carte a été avalée par le distributeur", phon: "Mah kart ah tay-tay ah-vah-LAY par luh dis-tree-bew-TORE", en: "My card was swallowed by the ATM", context: "Carte bloquée dans le distributeur" },
      { fr: "Je voudrais augmenter mon plafond", phon: "Juh voo-DRAY og-mahn-TAY mohn plah-FON", en: "I'd like to increase my limit", context: "Limite de carte bancaire" },
      { fr: "Je n'ai pas reçu mon relevé de compte", phon: "Juh nay pah ruh-SEW mohn ruh-luh-VAY duh kohnt", en: "I haven't received my bank statement", context: "Relevé manquant" },
      { fr: "Il y a une opération que je ne reconnais pas", phon: "Eel yah oon o-pay-rah-SYOHN kuh zhuh nuh ruh-kon-AY pah", en: "There's a transaction I don't recognise", context: "Fraude bancaire suspectée" },
      { fr: "Je voudrais envoyer un colis en [Corée]", phon: "Juh voo-DRAY ahn-vwah-YAY uhn koh-LEE ahn [koh-RAY]", en: "I'd like to send a parcel to [Korea]", context: "Envoyer un colis" },
      { fr: "Quel est le tarif pour un recommandé ?", phon: "Kel ay luh tah-REEF poor uhn ruh-kom-mahn-DAY", en: "What's the price for registered mail?", context: "Courrier recommandé" },
      { fr: "Je voudrais une lettre suivie", phon: "Juh voo-DRAY oon LET-truh swee-VEE", en: "I'd like tracked mail", context: "Suivi de courrier" },
      { fr: "Où est ma boîte postale ?", phon: "Oo ay mah bwat pohs-TAL", en: "Where is my PO box?", context: "Boîte postale" },
      { fr: "Le colis n'est pas arrivé", phon: "Luh koh-LEE nay pah ah-ree-VAY", en: "The parcel hasn't arrived", context: "Colis manquant" },
      { fr: "Je voudrais retirer de l'argent", phon: "Juh voo-DRAY ruh-tee-RAY duh lar-ZHAHN", en: "I'd like to withdraw money", context: "Retrait au guichet" },
      { fr: "Quels sont les frais à l'étranger ?", phon: "Kel sohn lay FRAY ah lay-TRAHN-ZHAY", en: "What are the foreign transaction fees?", context: "Frais bancaires à l'étranger" }
    ]
  },
  {
    id: 'ecole',
    icon: '🎒',
    title: "École de l'enfant",
    titleEn: "Child's School",
    color: '#EC4899',
    desc: 'Inscription, cantine, absence, professeurs',
    descEn: 'Enrollment, canteen, absence, teachers',
    phrases: [
      { fr: "Je voudrais inscrire mon enfant à l'école", phon: "Juh voo-DRAY zans-KREER mohn ahn-FAHN tah lay-KOL", en: "I'd like to enrol my child in school", context: "Inscription scolaire" },
      { fr: "Mon fils / Ma fille est malade et ne viendra pas aujourd'hui", phon: "Mohn fees / Mah fee ay mal-AHD ay nuh vee-DRAH pah oh-zhoor-DWEE", en: "My son / daughter is sick and won't come today", context: "Absence pour maladie" },
      { fr: "Mon enfant a une allergie alimentaire", phon: "Mohn ahn-FAHN ah oon al-lair-ZHEE ah-lee-mahn-TAIR", en: "My child has a food allergy", context: "ALLERGIE — informer l'école" },
      { fr: "Puis-je parler au directeur / à la directrice ?", phon: "Pwee zhuh par-LAY oh deer-ek-TORE / ah lah deer-ek-TREES", en: "Can I speak to the headteacher?", context: "Rendez-vous avec le directeur" },
      { fr: "Mon enfant se fait harceler", phon: "Mohn ahn-FAHN suh fay ar-suh-LAY", en: "My child is being bullied", context: "Harcèlement scolaire — URGENCE" },
      { fr: "Je voudrais un entretien avec le professeur", phon: "Juh voo-DRAY uhn ahn-truh-TYAN ah-VECK luh pro-fuh-SUR", en: "I'd like a meeting with the teacher", context: "Rencontre parents-professeurs" },
      { fr: "Quand sont les vacances scolaires ?", phon: "Kahn sohn lay vah-KAHNS skoh-LAIR", en: "When are the school holidays?", context: "Calendrier scolaire" },
      { fr: "Je voudrais changer le régime de cantine", phon: "Juh voo-DRAY shahn-ZHAY luh ray-ZHEEM duh kahn-TEEN", en: "I'd like to change the canteen meal plan", context: "Cantine (sans porc, allergie...)" },
      { fr: "Mon enfant a oublié son goûter", phon: "Mohn ahn-FAHN ah oo-blee-AY sohn goo-TAY", en: "My child forgot their snack", context: "Goûter oublié" },
      { fr: "Puis-je récupérer mon enfant plus tôt ?", phon: "Pwee zhuh ray-koo-pay-RAY mohn ahn-FAHNT ploo TOH", en: "Can I pick up my child earlier?", context: "Récupération anticipée" },
      { fr: "Quels sont les frais de scolarité ?", phon: "Kel sohn lay FRAY duh skoh-lah-ree-TAY", en: "What are the school fees?", context: "Frais d'inscription" },
      { fr: "Mon enfant a besoin d'un accompagnement spécialisé", phon: "Mohn ahn-FAHN ah buh-ZWAHN duhn ah-kohm-pah-nyah-MAHN spay-syah-lee-ZAY", en: "My child needs special support", context: "Handicap, difficultés d'apprentissage" },
      { fr: "Y a-t-il une garderie le soir ?", phon: "Ee ah-TEEL oon gar-DREE luh SWAR", en: "Is there after-school care?", context: "Garderie, étude surveillée" },
      { fr: "Je voudrais les bulletins scolaires", phon: "Juh voo-DRAY lay bool-tan skoh-LAIR", en: "I'd like the school reports", context: "Relevé de notes" },
      { fr: "Mon enfant arrive en cours de milieu d'année", phon: "Mohn ahn-FAHN ah-REEVE ahn koor duh mee-LYEW dah-NAY", en: "My child is arriving mid-year", context: "Arrivée en cours d'année scolaire" }
    ]
  },
  {
    id: 'restaurant',
    icon: '🍽️',
    title: 'Restaurant / Café',
    titleEn: 'Restaurant / Café',
    color: '#EA580C',
    desc: 'Réservation, commande, allergies, addition',
    descEn: 'Booking, ordering, allergies, bill',
    phrases: [
      { fr: "Je voudrais réserver une table pour [4] personnes", phon: "Juh voo-DRAY ray-zair-VAY oon tah-BLUH poor [katr] pair-SOHN", en: "I'd like to book a table for [4] people", context: "Réservation au restaurant" },
      { fr: "Nous sommes [deux adultes et un enfant]", phon: "Noo sohm [duh zoo ah-DOOL tay uhn ahn-FAHN]", en: "We are [two adults and one child]", context: "Préciser la composition du groupe" },
      { fr: "Je suis allergique aux fruits de mer", phon: "Juh swee al-lair-ZHEEK oh frwee duh mare", en: "I'm allergic to seafood", context: "Allergie alimentaire" },
      { fr: "Je ne mange pas de porc", phon: "Juh nuh MAHNZH pah duh por", en: "I don't eat pork", context: "Restriction alimentaire" },
      { fr: "Je suis végétarien / végétalien", phon: "Juh swee vay-zhay-tah-ree-AN / vay-zhay-tah-LEE-AN", en: "I'm vegetarian / vegan", context: "Régime alimentaire" },
      { fr: "Quelle est la spécialité de la maison ?", phon: "Kel ay lah spay-see-ah-lee-TAY duh lah may-ZOHN", en: "What is the house speciality?", context: "Demander le plat recommandé" },
      { fr: "L'addition, s'il vous plaît", phon: "Lah-dee-SYOHN, seel voo PLEH", en: "The bill, please", context: "Demander l'addition" },
      { fr: "Je voudrais un verre d'eau du robinet", phon: "Juh voo-DRAY uhn vair doh doo rob-ee-NAY", en: "I'd like a glass of tap water", context: "Eau gratuite au restaurant" },
      { fr: "C'était très bon, merci", phon: "Say-TAY tray bohn, mair-SEE", en: "It was very good, thank you", context: "Complimenter le repas" },
      { fr: "Puis-je avoir un doggy bag ?", phon: "Pwee zhuh ah-VWAIR uhn doggy bag", en: "Can I have a doggy bag?", context: "Emporter les restes" },
      { fr: "Le plat est trop salé / trop épicé", phon: "Luh plah ay troh sah-LAY / troh ay-pee-SAY", en: "The dish is too salty / too spicy", context: "Défaut du plat" },
      { fr: "Je voudrais commander à emporter", phon: "Juh voo-DRAY koh-mahn-DAY ah ahm-por-TAY", en: "I'd like to order takeaway", context: "Commande à emporter" },
      { fr: "Avez-vous un menu enfant ?", phon: "Ah-vay voo uhn muh-NEW ahn-FAHN", en: "Do you have a children's menu?", context: "Pour ton fils de 9 ans" },
      { fr: "Puis-je payer séparément ?", phon: "Pwee zhuh pay-YAY say-pah-ray-MAHN", en: "Can we pay separately?", context: "Partager l'addition" },
      { fr: "Le service est compris ?", phon: "Luh sair-VEES ay kohm-PREE", en: "Is service included?", context: "Pourboire" }
    ]
  },
  {
    id: 'telephone',
    icon: '📞',
    title: 'Au téléphone',
    titleEn: 'On the Phone',
    color: '#6366F1',
    desc: 'Appels importants, messages, comprendre',
    descEn: 'Important calls, messages, understanding',
    phrases: [
      { fr: "Je vous appelle au sujet de...", phon: "Juh voo zah-PEL oh soo-ZHAY duh...", en: "I'm calling about...", context: "Commencer un appel" },
      { fr: "Puis-je parler à [Monsieur Martin] ?", phon: "Pwee zhuh par-LAY ah [muh-SYEW mar-TAN]", en: "May I speak to [Mr Martin]?", context: "Demander une personne" },
      { fr: "C'est de la part de qui ?", phon: "Say duh lah par duh kee", en: "Who's calling?", context: "On vous demande qui vous êtes" },
      { fr: "Je vous rappellerai plus tard", phon: "Juh voo rah-play-RAY ploo tar", en: "I'll call you back later", context: "Rappeler plus tard" },
      { fr: "La ligne est occupée", phon: "lah LEEN ay tok-oo-PAY", en: "The line is busy", context: "Numéro occupé" },
      { fr: "Je n'ai pas bien compris, pouvez-vous répéter ?", phon: "Juh nay pah byan kohm-PREE, poo-vay voo ray-pay-TAY", en: "I didn't quite understand, could you repeat?", context: "ESSENTIEL — demander de répéter" },
      { fr: "Pourriez-vous parler plus lentement ?", phon: "Poo-ree-AY voo par-LAY ploo lahnt-MAHN", en: "Could you speak more slowly?", context: "Parler plus lentement" },
      { fr: "Pouvez-vous m'envoyer ça par mail ?", phon: "Poo-vay voo mahn-vwah-YAY sahn par mayl", en: "Can you send this to me by email?", context: "Demander un email" },
      { fr: "Je vous laisse mon numéro", phon: "Juh voo LESS mohn noo-MAY-roh", en: "I'll give you my number", context: "Laisser ses coordonnées" },
      { fr: "C'est urgent", phon: "Say toor-ZHAHN", en: "It's urgent", context: "Priorité de l'appel" },
      { fr: "Je voudrais prendre rendez-vous", phon: "Juh voo-DRAY PRON-druh rahn-day-VOO", en: "I'd like to make an appointment", context: "RDV par téléphone" },
      { fr: "Je suis bien chez [le Docteur Dupont] ?", phon: "Juh swee byan shay [luh dok-TORE doo-PON]", en: "Is this [Dr Dupont's office]?", context: "Vérifier le numéro" },
      { fr: "Pouvez-vous me passer [le service des impôts] ?", phon: "Poo-vay voo muh pah-SAY [luh sair-VEES day zan-POW]", en: "Can you put me through to [the tax office]?", context: "Transfert d'appel" },
      { fr: "Je vais vous mettre en attente", phon: "Juh vay voo may-TR ahn ah-TAHNT", en: "I'll put you on hold", context: "Quand on vous met en attente" },
      { fr: "Raccrochez et rappelez le 15", phon: "Rah-kroh-SHAY ay rah-play luh KANZ", en: "Hang up and call 15", context: "SAMU — urgences médicales" }
    ]
  }
];
