// lesson-18.js
const LESSON_18 = {
  id: 18, title: "My Health", titleFr: "Ma santé",
  objectiveEn: "Explain symptoms, make a doctor's appointment, go to the pharmacy", objectiveFr: "Expliquer les symptômes, prendre rendez-vous chez le médecin, aller à la pharmacie",
  hintEn: "J'ai mal à la/au/aux + body part = I have pain in...", hintFr: "J'ai mal à la/au/aux + partie du corps = j'ai mal à...",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"18-1",type:"qcm",question:"'I have a headache' in French:",questionFr:"Traduisez : 'J'ai mal à la tête.'",options:["J'ai mal à la tête.","J'ai mal la tête.","Je suis mal tête.","Ma tête fait mal."],optionsEn:["I have a headache.","I have pain the head (missing à)","I am bad head","My head hurts"],correct:"J'ai mal à la tête.",correctEn:"I have a headache.",explanation:"J'ai mal à = I have pain in.",explanationFr:"J'ai mal à = j'ai mal à."},
    {id:"18-2",type:"qcm",question:"'I have back pain' in French:",questionFr:"Traduisez : 'J'ai mal au dos.'",options:["J'ai mal au dos.","J'ai mal le dos.","J'ai dos mal.","Mon dos a mal."],optionsEn:["I have back pain.","I have pain the back","I have back pain (wrong order)","My back hurts"],correct:"J'ai mal au dos.",correctEn:"I have back pain.",explanation:"Au = à + le (dos masculine).",explanationFr:"Au = à + le (dos masculin)."},
    {id:"18-3",type:"qcm",question:"'I have a sore throat' in French:",questionFr:"Traduisez : 'J'ai mal à la gorge.'",options:["J'ai mal à la gorge.","J'ai mal la gorge.","Ma gorge est mal.","J'ai la gorge."],optionsEn:["I have a sore throat.","I have pain the throat","My throat is bad","I have the throat"],correct:"J'ai mal à la gorge.",correctEn:"I have a sore throat.",explanation:"À la gorge (feminine).",explanationFr:"À la gorge (féminin)."},
    {id:"18-4",type:"qcm",question:"'I have toothache' in French:",questionFr:"Traduisez : 'J'ai mal aux dents.'",options:["J'ai mal aux dents.","J'ai mal les dents.","Mes dents ont mal.","J'ai les dents mal."],optionsEn:["I have toothache.","I have pain the teeth","My teeth hurt","I have the teeth bad"],correct:"J'ai mal aux dents.",correctEn:"I have toothache.",explanation:"Aux = à + les (dents plural).",explanationFr:"Aux = à + les (dents pluriel)."},
    {id:"18-5",type:"qcm",question:"'I would like to make an appointment' in French:",questionFr:"Traduisez : 'Je voudrais prendre rendez-vous.'",options:["Je voudrais prendre rendez-vous.","Je dois faire rendez-vous.","Je veux rendez-vous.","Prenez rendez-vous."],optionsEn:["I would like to make an appointment.","I must make an appointment.","I want an appointment.","Make an appointment (imperative)."],correct:"Je voudrais prendre rendez-vous.",correctEn:"I would like to make an appointment.",explanation:"Prendre rendez-vous = to make an appointment.",explanationFr:"Prendre rendez-vous = prendre rendez-vous."},
    {id:"18-6",type:"qcm",question:"'The emergency room' in French:",questionFr:"Comment dit-on 'les urgences' ?",options:["Les urgences","Les urgents","L'urgence","Le service urgent"],optionsEn:["The emergency room","The urgent (plural)","The urgency","The urgent service"],correct:"Les urgences",correctEn:"The emergency room",explanation:"Urgences = A&E (always plural).",explanationFr:"Urgences = urgences (toujours pluriel)."},
    {id:"18-7",type:"qcm",question:"'I've been ill for 3 days' in French:",questionFr:"Traduisez : 'Je suis malade depuis trois jours.'",options:["Je suis malade depuis trois jours.","J'ai malade trois jours.","Je suis malade pour trois jours.","Depuis je suis malade trois jours."],optionsEn:["I've been ill for 3 days.","I have ill three days","I am ill for three days","Since I am ill three days"],correct:"Je suis malade depuis trois jours.",correctEn:"I've been ill for 3 days.",explanation:"Depuis = for (with present tense).",explanationFr:"Depuis = depuis (avec présent)."},
    {id:"18-8",type:"qcm",question:"'I take medication' in French:",questionFr:"Traduisez : 'Je prends un médicament.'",options:["Je prends un médicament.","J'ai un médicament.","Je suis médicament.","Je fais médicament."],optionsEn:["I take medication.","I have medication.","I am medication.","I do medication."],correct:"Je prends un médicament.",correctEn:"I take medication.",explanation:"Prendre = to take.",explanationFr:"Prendre = prendre."},
    {id:"18-9",type:"qcm",question:"'I am feeling ill' in French:",questionFr:"Traduisez : 'Je suis malade.'",options:["Je suis malade.","J'ai malade.","Je fais malade.","Je me suis malade."],optionsEn:["I am ill.","I have ill","I do ill","I am ill (refl)"],correct:"Je suis malade.",correctEn:"I am ill.",explanation:"Être malade = to be ill.",explanationFr:"Être malade = être malade."},
    {id:"18-10",type:"qcm",question:"Which is correct: 'My back hurts'?",questionFr:"Lequel est correct : 'J'ai mal au dos' ?",options:["J'ai mal au dos.","J'ai mal le dos.","Mon dos a mal.","Je suis mal au dos."],optionsEn:["I have back pain (correct)","I have pain the back","My back hurts","I am bad to the back"],correct:"J'ai mal au dos.",correctEn:"I have back pain.",explanation:"Only J'ai mal au dos is correct.",explanationFr:"Seul J'ai mal au dos est correct."}
  ],
  libre: [
    {id:"18-l1",type:"libre",question:"Translate: 'I have a headache.'",questionFr:"Traduisez : 'J'ai mal à la tête.'",correct:"J'ai mal à la tête.",correctEn:"I have a headache.",alternatives:[],explanation:"À la tête (feminine).",explanationFr:"À la tête (féminin)."},
    {id:"18-l2",type:"libre",question:"Translate: 'I have back pain.'",questionFr:"Traduisez : 'J'ai mal au dos.'",correct:"J'ai mal au dos.",correctEn:"I have back pain.",alternatives:[],explanation:"Au dos = à + le dos.",explanationFr:"Au dos = à + le dos."},
    {id:"18-l3",type:"libre",question:"How do you say 'I have toothache'?",questionFr:"Comment dit-on 'J'ai mal aux dents' ?",correct:"J'ai mal aux dents.",correctEn:"I have toothache.",alternatives:[],explanation:"Aux dents = à + les dents.",explanationFr:"Aux dents = à + les dents."},
    {id:"18-l4",type:"libre",question:"Complete: 'J'ai mal ___ gorge.'",questionFr:"Complétez : 'J'ai mal ___ gorge.'",correct:"à la",correctEn:"to the",alternatives:[],explanation:"À la gorge (feminine).",explanationFr:"À la gorge (féminin)."},
    {id:"18-l5",type:"libre",question:"Translate: 'I would like to make an appointment for tomorrow.'",questionFr:"Traduisez : 'Je voudrais prendre rendez-vous pour demain.'",correct:"Je voudrais prendre rendez-vous pour demain.",correctEn:"I would like to make an appointment for tomorrow.",alternatives:[],explanation:"Pour demain = for tomorrow.",explanationFr:"Pour demain = pour demain."},
    {id:"18-l6",type:"libre",question:"How do you say 'I am ill'?",questionFr:"Comment dit-on 'Je suis malade' ?",correct:"Je suis malade.",correctEn:"I am ill.",alternatives:[],explanation:"Être malade.",explanationFr:"Être malade."},
    {id:"18-l7",type:"libre",question:"Translate: 'I've had a headache for two days.'",questionFr:"Traduisez : 'J'ai mal à la tête depuis deux jours.'",correct:"J'ai mal à la tête depuis deux jours.",correctEn:"I've had a headache for two days.",alternatives:[],explanation:"Depuis = for.",explanationFr:"Depuis = depuis."},
    {id:"18-l8",type:"libre",question:"What is 'les urgences'?",questionFr:"Qu'est-ce que 'les urgences' ?",correct:"the emergency room",correctEn:"the emergency room",alternatives:["A&E","emergency room"],explanation:"Les urgences = A&E.",explanationFr:"Les urgences = les urgences."},
    {id:"18-l9",type:"libre",question:"Complete: 'Je ___ un médicament contre la douleur.'",questionFr:"Complétez : 'Je ___ un médicament contre la douleur.'",correct:"prends",correctEn:"take",alternatives:[],explanation:"Prendre = to take.",explanationFr:"Prendre = prendre."},
    {id:"18-l10",type:"libre",question:"Translate: 'I have a stomach ache.'",questionFr:"Traduisez : 'J'ai mal au ventre.'",correct:"J'ai mal au ventre.",correctEn:"I have a stomach ache.",alternatives:[],explanation:"Au ventre (masculine).",explanationFr:"Au ventre (masculin)."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_18; else window.LESSON_18 = LESSON_18;
