// lesson-14.js
const LESSON_14 = {
  id: 14, title: "My Needs", titleFr: "Mes besoins",
  objectiveEn: "Express hunger, thirst, tiredness and desires using avoir", objectiveFr: "Exprimer la faim, la soif, la fatigue et les désirs en utilisant avoir",
  hintEn: "Hunger and thirst use AVOIR, not être!", hintFr: "La faim et la soif utilisent AVOIR, pas être !",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"14-1",type:"qcm",question:"'I am hungry' in French:",questionFr:"Traduisez : 'J'ai faim.'",options:["J'ai faim.","Je suis faim.","J'ai famine.","Je fais faim."],optionsEn:["I am hungry.","I am hunger (wrong)","I have famine","I do hunger"],correct:"J'ai faim.",correctEn:"I am hungry",explanation:"Avoir faim = to be hungry.",explanationFr:"Avoir faim = avoir faim."},
    {id:"14-2",type:"qcm",question:"'I am thirsty' in French:",questionFr:"Traduisez : 'J'ai soif.'",options:["J'ai soif.","Je suis soif.","J'ai soife.","Je soif."],optionsEn:["I am thirsty.","I am thirst (wrong)","I have thirst (wrong spelling)","I thirst"],correct:"J'ai soif.",correctEn:"I am thirsty",explanation:"Avoir soif = to be thirsty.",explanationFr:"Avoir soif = avoir soif."},
    {id:"14-3",type:"qcm",question:"'I am sleepy' in French:",questionFr:"Traduisez : 'J'ai sommeil.'",options:["J'ai sommeil.","Je suis sommeil.","J'ai dormi.","Je me dors."],optionsEn:["I am sleepy.","I am sleep (wrong)","I slept","I sleep (refl)"],correct:"J'ai sommeil.",correctEn:"I am sleepy",explanation:"Avoir sommeil = to be sleepy.",explanationFr:"Avoir sommeil = avoir sommeil."},
    {id:"14-4",type:"qcm",question:"'I need to rest' in French:",questionFr:"Traduisez : 'J'ai besoin de me reposer.'",options:["J'ai besoin de me reposer.","Je besoin reposer.","J'ai need reposer.","J'ai besoin repose."],optionsEn:["I need to rest.","I need rest (no de)","I need (English) rest","I need rest (noun)"],correct:"J'ai besoin de me reposer.",correctEn:"I need to rest.",explanation:"Avoir besoin de = to need.",explanationFr:"Avoir besoin de = avoir besoin de."},
    {id:"14-5",type:"qcm",question:"'I feel like going for a walk' in French:",questionFr:"Traduisez : 'J'ai envie de me promener.'",options:["J'ai envie de me promener.","Je veux me promener.","J'ai envie promener.","Je me promène."],optionsEn:["I feel like going for a walk.","I want to go for a walk.","I feel like go for a walk (missing de)","I go for a walk."],correct:"J'ai envie de me promener.",correctEn:"I feel like going for a walk.",explanation:"Avoir envie de = to feel like.",explanationFr:"Avoir envie de = avoir envie de."},
    {id:"14-6",type:"qcm",question:"The POLITE way to say 'I want a coffee' in French:",questionFr:"La façon POLIE de dire 'Je veux un café' en français :",options:["Je voudrais un café, s'il vous plaît.","Je veux un café.","Donnez-moi un café.","Un café !"],optionsEn:["I would like a coffee, please.","I want a coffee.","Give me a coffee.","A coffee!"],correct:"Je voudrais un café, s'il vous plaît.",correctEn:"I would like a coffee, please.",explanation:"Je voudrais (conditional) is polite.",explanationFr:"Je voudrais (conditionnel) est poli."},
    {id:"14-7",type:"qcm",question:"'I need some rest.' in French:",questionFr:"Traduisez : 'J'ai besoin de repos.'",options:["J'ai besoin de repos.","Je besoin repos.","J'ai repos.","Je suis besoin repos."],optionsEn:["I need some rest.","I need rest (no avoir)","I have rest","I am need rest"],correct:"J'ai besoin de repos.",correctEn:"I need some rest.",explanation:"Avoir besoin de + noun.",explanationFr:"Avoir besoin de + nom."},
    {id:"14-8",type:"qcm",question:"'I don't feel like going out.' in French:",questionFr:"Traduisez : 'Je n'ai pas envie de sortir.'",options:["Je n'ai pas envie de sortir.","Je veux pas sortir.","J'ai pas envie.","Je ne veux pas."],optionsEn:["I don't feel like going out.","I don't want to go out.","I don't feel like (incomplete)","I don't want to."],correct:"Je n'ai pas envie de sortir.",correctEn:"I don't feel like going out.",explanation:"Negative of avoir envie.",explanationFr:"Négation de avoir envie."},
    {id:"14-9",type:"qcm",question:"'I need help.' in French:",questionFr:"Traduisez : 'J'ai besoin d'aide.'",options:["J'ai besoin d'aide.","Je besoin aide.","J'ai aide.","Je dois aide."],optionsEn:["I need help.","I need help (no avoir)","I have help","I must help"],correct:"J'ai besoin d'aide.",correctEn:"I need help.",explanation:"Avoir besoin d'aide = to need help.",explanationFr:"Avoir besoin d'aide = avoir besoin d'aide."},
    {id:"14-10",type:"qcm",question:"'Would you like some water?' (polite) in French:",questionFr:"Comment dit-on 'Voudriez-vous de l'eau ?' (poli)",options:["Voudriez-vous de l'eau ?","Voulez-vous eau ?","Avez-vous soif ?","De l'eau vous plaît ?"],optionsEn:["Would you like some water?","Do you want water?","Are you thirsty?","Water please you?"],correct:"Voudriez-vous de l'eau ?",correctEn:"Would you like some water?",explanation:"Voudriez-vous (conditional) = would you like.",explanationFr:"Voudriez-vous (conditionnel) = voudriez-vous."}
  ],
  libre: [
    {id:"14-l1",type:"libre",question:"Translate: 'I am hungry.'",questionFr:"Traduisez : 'J'ai faim.'",correct:"J'ai faim.",correctEn:"I am hungry.",alternatives:[],explanation:"Avoir faim.",explanationFr:"Avoir faim."},
    {id:"14-l2",type:"libre",question:"Translate: 'I am thirsty.'",questionFr:"Traduisez : 'J'ai soif.'",correct:"J'ai soif.",correctEn:"I am thirsty.",alternatives:[],explanation:"Avoir soif.",explanationFr:"Avoir soif."},
    {id:"14-l3",type:"libre",question:"How do you say 'I need to call the doctor'?",questionFr:"Comment dit-on 'J'ai besoin d'appeler le médecin' ?",correct:"J'ai besoin d'appeler le médecin.",correctEn:"I need to call the doctor.",alternatives:[],explanation:"Avoir besoin de + infinitive.",explanationFr:"Avoir besoin de + infinitif."},
    {id:"14-l4",type:"libre",question:"Complete: 'J'ai ___ de dormir.'",questionFr:"Complétez : 'J'ai ___ de dormir.'",correct:"besoin",correctEn:"need",alternatives:[],explanation:"Avoir besoin de = to need.",explanationFr:"Avoir besoin de = avoir besoin de."},
    {id:"14-l5",type:"libre",question:"Translate: 'I feel like a coffee.'",questionFr:"Traduisez : 'J'ai envie d'un café.'",correct:"J'ai envie d'un café.",correctEn:"I feel like a coffee.",alternatives:[],explanation:"Avoir envie de = to feel like.",explanationFr:"Avoir envie de = avoir envie de."},
    {id:"14-l6",type:"libre",question:"How do you say 'I would like some bread, please'?",questionFr:"Comment dit-on 'Je voudrais du pain, s'il vous plaît' ?",correct:"Je voudrais du pain, s'il vous plaît.",correctEn:"I would like some bread, please.",alternatives:[],explanation:"Je voudrais = I would like.",explanationFr:"Je voudrais = je voudrais."},
    {id:"14-l7",type:"libre",question:"Complete: 'Je ___ pas envie de cuisiner ce soir.'",questionFr:"Complétez : 'Je ___ pas envie de cuisiner ce soir.'",correct:"n'ai",correctEn:"don't have",alternatives:[],explanation:"Je n'ai pas envie = I don't feel like.",explanationFr:"Je n'ai pas envie = je n'ai pas envie."},
    {id:"14-l8",type:"libre",question:"Translate: 'I need some help.'",questionFr:"Traduisez : 'J'ai besoin d'aide.'",correct:"J'ai besoin d'aide.",correctEn:"I need some help.",alternatives:[],explanation:"Avoir besoin d'aide.",explanationFr:"Avoir besoin d'aide."},
    {id:"14-l9",type:"libre",question:"What's the polite way to say 'I want'?",questionFr:"Quelle est la façon polie de dire 'Je veux' ?",correct:"Je voudrais",correctEn:"I would like",alternatives:[],explanation:"Je voudrais (conditional) is polite.",explanationFr:"Je voudrais (conditionnel) est poli."},
    {id:"14-l10",type:"libre",question:"Translate: 'I am not hungry.'",questionFr:"Traduisez : 'Je n'ai pas faim.'",correct:"Je n'ai pas faim.",correctEn:"I am not hungry.",alternatives:[],explanation:"Negative of avoir faim.",explanationFr:"Négation de avoir faim."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_14; else window.LESSON_14 = LESSON_14;
