// lesson-07.js
const LESSON_07 = {
  id: 7, title: "Friends & Going Out", titleFr: "Amis et sorties",
  objectiveEn: "Make and accept social invitations, arrange to meet", objectiveFr: "Faire et accepter des invitations, organiser des rencontres",
  hintEn: "'Ça vous dit de...' is the most natural way to invite someone!", hintFr: "'Ça vous dit de...' est la façon la plus naturelle d'inviter quelqu'un !",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"7-1",type:"qcm",question:"'Would you like to go to a restaurant?' in French:",questionFr:"Traduisez : 'Ça vous dit d'aller au restaurant ?'",options:["Ça vous dit d'aller au restaurant ?","Voulez-vous restaurant ?","Vous aimez restaurant ?","On va restaurant ?"],optionsEn:["Would you like to go to a restaurant?","Do you want restaurant?","Do you like restaurant?","We go restaurant?"],correct:"Ça vous dit d'aller au restaurant ?",correctEn:"Would you like to go to a restaurant?",explanation:"Ça vous dit de = would you like to.",explanationFr:"Ça vous dit de = ça vous dit de."},
    {id:"7-2",type:"qcm",question:"'I'm free on Saturday.' in French:",questionFr:"Traduisez : 'Je suis libre samedi.'",options:["Je suis libre samedi.","J'ai libre samedi.","Je peux samedi.","Samedi je veux."],optionsEn:["I'm free on Saturday.","I have free Saturday.","I can Saturday.","Saturday I want."],correct:"Je suis libre samedi.",correctEn:"I'm free on Saturday.",explanation:"Libre = free.",explanationFr:"Libre = libre."},
    {id:"7-3",type:"qcm",question:"'Where shall we meet?' in French:",questionFr:"Traduisez : 'On se retrouve où ?'",options:["On se retrouve où ?","Où on va ?","On se voit comment ?","Où se rencontrer ?"],optionsEn:["Where shall we meet?","Where do we go?","How do we see each other?","Where to meet?"],correct:"On se retrouve où ?",correctEn:"Where shall we meet?",explanation:"On se retrouve = we meet up.",explanationFr:"On se retrouve = on se retrouve."},
    {id:"7-4",type:"qcm",question:"'With pleasure!' in French:",questionFr:"Comment dit-on 'Avec plaisir !' ?",options:["Avec plaisir !","Oui bien sûr !","Pourquoi pas !","D'accord !"],optionsEn:["With pleasure!","Yes of course!","Why not!","Okay!"],correct:"Avec plaisir !",correctEn:"With pleasure!",explanation:"Avec plaisir = with pleasure.",explanationFr:"Avec plaisir = avec plaisir."},
    {id:"7-5",type:"qcm",question:"'I'm sorry, I can't on Friday.' in French:",questionFr:"Traduisez : 'Je suis désolé(e), je ne peux pas vendredi.'",options:["Je suis désolé(e), je ne peux pas vendredi.","Je peux pas vendredi.","Vendredi non.","Désolé vendredi."],optionsEn:["I'm sorry, I can't on Friday.","I can't on Friday.","Friday no.","Sorry Friday."],correct:"Je suis désolé(e), je ne peux pas vendredi.",correctEn:"I'm sorry, I can't on Friday.",explanation:"Je ne peux pas = I can't.",explanationFr:"Je ne peux pas = je ne peux pas."},
    {id:"7-6",type:"qcm",question:"'At what time?' in French:",questionFr:"Comment dit-on 'À quelle heure ?'",options:["À quelle heure ?","Quelle heure est ?","Quand heure ?","C'est l'heure ?"],optionsEn:["At what time?","What time is it?","When hour?","Is it time?"],correct:"À quelle heure ?",correctEn:"At what time?",explanation:"À quelle heure = at what time.",explanationFr:"À quelle heure = à quelle heure."},
    {id:"7-7",type:"qcm",question:"'Let's go for a walk.' in French:",questionFr:"Traduisez : 'On va se promener.'",options:["On va se promener.","On fait promenade.","Allons promenade.","On marche."],optionsEn:["Let's go for a walk.","We do a walk.","Let's go walk.","We walk."],correct:"On va se promener.",correctEn:"Let's go for a walk.",explanation:"On va + infinitive = let's go.",explanationFr:"On va + infinitif = on va."},
    {id:"7-8",type:"qcm",question:"'Maybe next time.' in French:",questionFr:"Traduisez : 'Peut-être la prochaine fois.'",options:["Peut-être la prochaine fois.","Peut-être après.","Prochain temps.","Une autre fois peut-être."],optionsEn:["Maybe next time.","Maybe after.","Next time.","Another time maybe."],correct:"Peut-être la prochaine fois.",correctEn:"Maybe next time.",explanation:"Peut-être = maybe.",explanationFr:"Peut-être = peut-être."},
    {id:"7-9",type:"qcm",question:"'Good idea!' in French:",questionFr:"Comment dit-on 'Bonne idée !' ?",options:["Bonne idée !","Bon idée !","C'est idée !","Idée bien !"],optionsEn:["Good idea!","Good idea (masculine wrong)","It's idea!","Idea good!"],correct:"Bonne idée !",correctEn:"Good idea!",explanation:"Idée is feminine -> bonne.",explanationFr:"Idée est féminin -> bonne."},
    {id:"7-10",type:"qcm",question:"'See you Saturday!' in French:",questionFr:"Traduisez : 'À samedi !'",options:["À samedi !","Samedi à vous !","Bonjour samedi !","Samedi voir !"],optionsEn:["See you Saturday!","Saturday to you!","Hello Saturday!","Saturday see!"],correct:"À samedi !",correctEn:"See you Saturday!",explanation:"À + day = see you on day.",explanationFr:"À + jour = à jour."}
  ],
  libre: [
    {id:"7-l1",type:"libre",question:"Invite your neighbour for coffee.",questionFr:"Invitez votre voisin pour un café.",correct:"Ça vous dit de prendre un café ?",correctEn:"Would you like to have a coffee?",alternatives:["Ça vous dirait de prendre un café ?"],explanation:"Ça vous dit de + infinitive.",explanationFr:"Ça vous dit de + infinitif."},
    {id:"7-l2",type:"libre",question:"Translate: 'I'm free this weekend.'",questionFr:"Traduisez : 'Je suis libre ce week-end.'",correct:"Je suis libre ce week-end.",correctEn:"I'm free this weekend.",alternatives:[],explanation:"Ce week-end = this weekend.",explanationFr:"Ce week-end = ce week-end."},
    {id:"7-l3",type:"libre",question:"How do you say 'See you tomorrow'?",questionFr:"Comment dit-on 'À demain' ?",correct:"À demain !",correctEn:"See you tomorrow!",alternatives:[],explanation:"À demain = see you tomorrow.",explanationFr:"À demain = à demain."},
    {id:"7-l4",type:"libre",question:"Complete: 'On se retrouve ___ quelle heure ?'",questionFr:"Complétez : 'On se retrouve ___ quelle heure ?'",correct:"à",correctEn:"at",alternatives:[],explanation:"À quelle heure = at what time.",explanationFr:"À quelle heure = à quelle heure."},
    {id:"7-l5",type:"libre",question:"Translate: 'Sorry, I can't on Sunday.'",questionFr:"Traduisez : 'Désolé(e), je ne peux pas dimanche.'",correct:"Désolé(e), je ne peux pas dimanche.",correctEn:"Sorry, I can't on Sunday.",alternatives:["Je suis désolé, je ne peux pas dimanche."],explanation:"Je ne peux pas = I can't.",explanationFr:"Je ne peux pas = je ne peux pas."},
    {id:"7-l6",type:"libre",question:"How do you say 'Good idea!'?",questionFr:"Comment dit-on 'Bonne idée !' ?",correct:"Bonne idée !",correctEn:"Good idea!",alternatives:[],explanation:"Bonne idée.",explanationFr:"Bonne idée."},
    {id:"7-l7",type:"libre",question:"Translate: 'Let's go for a walk in the village.'",questionFr:"Traduisez : 'On va se promener dans le village.'",correct:"On va se promener dans le village.",correctEn:"Let's go for a walk in the village.",alternatives:[],explanation:"Se promener = to walk.",explanationFr:"Se promener = se promener."},
    {id:"7-l8",type:"libre",question:"Complete: 'Je suis ___ jeudi.'",questionFr:"Complétez : 'Je suis ___ jeudi.' (libre)",correct:"libre",correctEn:"free",alternatives:[],explanation:"Je suis libre = I'm free.",explanationFr:"Je suis libre = je suis libre."},
    {id:"7-l9",type:"libre",question:"How do you say 'With pleasure!'?",questionFr:"Comment dit-on 'Avec plaisir !' ?",correct:"Avec plaisir !",correctEn:"With pleasure!",alternatives:[],explanation:"Avec plaisir.",explanationFr:"Avec plaisir."},
    {id:"7-l10",type:"libre",question:"Translate: 'What time shall we meet?'",questionFr:"Traduisez : 'On se retrouve à quelle heure ?'",correct:"On se retrouve à quelle heure ?",correctEn:"What time shall we meet?",alternatives:[],explanation:"On se retrouve = we meet.",explanationFr:"On se retrouve = on se retrouve."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_07; else window.LESSON_07 = LESSON_07;
