// lesson-16.js
const LESSON_16 = {
  id: 16, title: "My Family", titleFr: "Ma famille",
  objectiveEn: "Talk about family members and use possessives correctly", objectiveFr: "Parler des membres de la famille et utiliser correctement les possessifs",
  hintEn: "Mon before masculine, ma before feminine, mes for plural — except before vowels: mon amie!", hintFr: "Mon avant le masculin, ma avant le féminin, mes pour le pluriel — sauf devant voyelle : mon amie !",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"16-1",type:"qcm",question:"'My husband' in French:",questionFr:"Comment dit-on 'mon mari' ?",options:["Mon mari","Ma mari","Mon homme","Le mari mien"],optionsEn:["My husband","My husband (wrong gender)","My man","The husband mine"],correct:"Mon mari",correctEn:"My husband",explanation:"Mon = masculine possessive.",explanationFr:"Mon = possessif masculin."},
    {id:"16-2",type:"qcm",question:"'My wife' in French:",questionFr:"Comment dit-on 'ma femme' ?",options:["Ma femme","Mon femme","Ma wife","La femme moi"],optionsEn:["My wife","My wife (wrong gender)","My wife (English)","The wife me"],correct:"Ma femme",correctEn:"My wife",explanation:"Ma = feminine possessive.",explanationFr:"Ma = possessif féminin."},
    {id:"16-3",type:"qcm",question:"'My son' in French:",questionFr:"Comment dit-on 'mon fils' ?",options:["Mon fils","Ma fils","Mon fiston","Le fils mien"],optionsEn:["My son","My son (wrong)","My son (diminutive)","The son mine"],correct:"Mon fils",correctEn:"My son",explanation:"Mon fils = my son.",explanationFr:"Mon fils = mon fils."},
    {id:"16-4",type:"qcm",question:"'My daughter' in French:",questionFr:"Comment dit-on 'ma fille' ?",options:["Ma fille","Mon fille","Ma girl","La fille mien"],optionsEn:["My daughter","My daughter (wrong)","My girl (English)","The daughter mine"],correct:"Ma fille",correctEn:"My daughter",explanation:"Ma fille = my daughter.",explanationFr:"Ma fille = ma fille."},
    {id:"16-5",type:"qcm",question:"'My grandchildren' in French:",questionFr:"Comment dit-on 'mes petits-enfants' ?",options:["Mes petits-enfants","Mon petit-enfant","Ma petits-enfants","Les petits-enfants miens"],optionsEn:["My grandchildren","My grandchild","My (fem) grandchildren","The grandchildren mine"],correct:"Mes petits-enfants",correctEn:"My grandchildren",explanation:"Mes = plural possessive.",explanationFr:"Mes = possessif pluriel."},
    {id:"16-6",type:"qcm",question:"'I have two children' in French:",questionFr:"Traduisez : 'J'ai deux enfants.'",options:["J'ai deux enfants.","Je suis deux enfants.","J'ai deux enfants miens.","Deux enfants j'ai."],optionsEn:["I have two children.","I am two children.","I have two children mine.","Two children I have."],correct:"J'ai deux enfants.",correctEn:"I have two children.",explanation:"Avoir for possession.",explanationFr:"Avoir pour la possession."},
    {id:"16-7",type:"qcm",question:"'My brother' in French:",questionFr:"Comment dit-on 'mon frère' ?",options:["Mon frère","Ma frère","Mon brother","Le frère mien"],optionsEn:["My brother","My brother (wrong gender)","My brother (English)","The brother mine"],correct:"Mon frère",correctEn:"My brother",explanation:"Mon frère = my brother.",explanationFr:"Mon frère = mon frère."},
    {id:"16-8",type:"qcm",question:"'My female friend' — why is it 'mon amie' not 'ma amie'?",questionFr:"'Mon amie' (pour une amie) — pourquoi pas 'ma amie' ?",options:["Because amie starts with a vowel","Because amie is masculine","Because it's wrong","No reason"],optionsEn:["Because amie starts with a vowel","Because amie is masculine","Because it's wrong","No reason"],correct:"Because amie starts with a vowel",correctEn:"Because amie starts with a vowel",explanation:"Use mon before vowels even with feminine.",explanationFr:"Utilisez mon devant voyelle même avec féminin."},
    {id:"16-9",type:"qcm",question:"'My parents' in French:",questionFr:"Comment dit-on 'mes parents' ?",options:["Mes parents","Mon parent","Ma parents","Les parents miens"],optionsEn:["My parents","My parent","My (fem) parents","The parents mine"],correct:"Mes parents",correctEn:"My parents",explanation:"Mes parents = my parents.",explanationFr:"Mes parents = mes parents."},
    {id:"16-10",type:"qcm",question:"'We have three grandchildren' in French:",questionFr:"Traduisez : 'Nous avons trois petits-enfants.'",options:["Nous avons trois petits-enfants.","Nous sommes trois petits-enfants.","On a trois petits-enfants.","Nos petits-enfants sont trois."],optionsEn:["We have three grandchildren.","We are three grandchildren.","We have three grandchildren (informal)","Our grandchildren are three."],correct:"Nous avons trois petits-enfants.",correctEn:"We have three grandchildren.",explanation:"Nous avons = we have.",explanationFr:"Nous avons = nous avons."}
  ],
  libre: [
    {id:"16-l1",type:"libre",question:"Translate: 'My husband is retired.'",questionFr:"Traduisez : 'Mon mari est retraité.'",correct:"Mon mari est retraité.",correctEn:"My husband is retired.",alternatives:[],explanation:"Retraité = retired.",explanationFr:"Retraité = retraité."},
    {id:"16-l2",type:"libre",question:"How do you say 'I have two daughters'?",questionFr:"Comment dit-on 'J'ai deux filles' ?",correct:"J'ai deux filles.",correctEn:"I have two daughters.",alternatives:[],explanation:"Deux filles = two daughters.",explanationFr:"Deux filles = deux filles."},
    {id:"16-l3",type:"libre",question:"Complete: '___ mère habite en Angleterre.'",questionFr:"Complétez : '___ mère habite en Angleterre.'",correct:"Ma",correctEn:"My",alternatives:[],explanation:"Ma mère = my mother.",explanationFr:"Ma mère = ma mère."},
    {id:"16-l4",type:"libre",question:"Translate: 'My children live in France.'",questionFr:"Traduisez : 'Mes enfants habitent en France.'",correct:"Mes enfants habitent en France.",correctEn:"My children live in France.",alternatives:[],explanation:"Mes = my (plural).",explanationFr:"Mes = mes (pluriel)."},
    {id:"16-l5",type:"libre",question:"How do you say 'my sister'?",questionFr:"Comment dit-on 'ma sœur' ?",correct:"ma sœur",correctEn:"my sister",alternatives:[],explanation:"Ma sœur = my sister.",explanationFr:"Ma sœur = ma sœur."},
    {id:"16-l6",type:"libre",question:"Complete: '___ amie s'appelle Helen.' (my female friend)",questionFr:"Complétez : '___ amie s'appelle Helen.' (mon amie)",correct:"Mon",correctEn:"My",alternatives:[],explanation:"Mon amie (before vowel).",explanationFr:"Mon amie (devant voyelle)."},
    {id:"16-l7",type:"libre",question:"Translate: 'I have four grandchildren.'",questionFr:"Traduisez : 'J'ai quatre petits-enfants.'",correct:"J'ai quatre petits-enfants.",correctEn:"I have four grandchildren.",alternatives:[],explanation:"Quatre = four.",explanationFr:"Quatre = quatre."},
    {id:"16-l8",type:"libre",question:"What is 'mes parents' in English?",questionFr:"Que signifie 'mes parents' en anglais ?",correct:"my parents",correctEn:"my parents",alternatives:[],explanation:"Mes parents = my parents.",explanationFr:"Mes parents = mes parents."},
    {id:"16-l9",type:"libre",question:"Translate: 'My son is a doctor.'",questionFr:"Traduisez : 'Mon fils est médecin.'",correct:"Mon fils est médecin.",correctEn:"My son is a doctor.",alternatives:[],explanation:"Médecin = doctor (no article).",explanationFr:"Médecin = médecin (pas d'article)."},
    {id:"16-l10",type:"libre",question:"Complete: 'J'ai ___ enfants.' (2,3,4,5)",questionFr:"Complétez : 'J'ai ___ enfants.'",correct:"deux",correctEn:"two",alternatives:["trois","quatre","cinq"],explanation:"Number + noun (no article).",explanationFr:"Nombre + nom (pas d'article)."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_16; else window.LESSON_16 = LESSON_16;
