// lesson-17.js
const LESSON_17 = {
  id: 17, title: "My Plans", titleFr: "Mes projets",
  objectiveEn: "Talk about future plans using futur proche (aller + infinitive)", objectiveFr: "Parler des projets futurs en utilisant le futur proche (aller + infinitif)",
  hintEn: "Futur proche = aller + infinitive. Simpler than future tense!", hintFr: "Futur proche = aller + infinitif. Plus simple que le futur simple !",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"17-1",type:"qcm",question:"'I am going to cook' in French:",questionFr:"Traduisez : 'Je vais cuisiner.'",options:["Je vais cuisiner.","Je suis cuisiner.","J'ai cuisiné.","Je cuisine."],optionsEn:["I am going to cook.","I am cook (wrong)","I cooked","I cook"],correct:"Je vais cuisiner.",correctEn:"I am going to cook.",explanation:"Futur proche: aller + infinitive.",explanationFr:"Futur proche : aller + infinitif."},
    {id:"17-2",type:"qcm",question:"'She is going to phone' in French:",questionFr:"Traduisez : 'Elle va téléphoner.'",options:["Elle va téléphoner.","Elle est téléphoner.","Elle va téléphone.","Elle ira téléphoner."],optionsEn:["She is going to phone.","She is phone (wrong)","She goes phone (noun)","She will phone"],correct:"Elle va téléphoner.",correctEn:"She is going to phone.",explanation:"Elle va + infinitive.",explanationFr:"Elle va + infinitif."},
    {id:"17-3",type:"qcm",question:"'Next week' in French:",questionFr:"Comment dit-on 'la semaine prochaine' ?",options:["La semaine prochaine","La prochaine semaine","Semaine prochaine","Next week"],optionsEn:["Next week","Next week (adj before noun)","Week next","Next week (English)"],correct:"La semaine prochaine",correctEn:"Next week",explanation:"Semaine prochaine = next week.",explanationFr:"Semaine prochaine = semaine prochaine."},
    {id:"17-4",type:"qcm",question:"'This weekend' in French:",questionFr:"Comment dit-on 'ce week-end' ?",options:["Ce week-end","Ce fin de semaine","Ce weekend","Ce we"],optionsEn:["This weekend","This end of week","This weekend (alt spelling)","This we (slang)"],correct:"Ce week-end",correctEn:"This weekend",explanation:"Week-end = weekend (French).",explanationFr:"Week-end = week-end (français)."},
    {id:"17-5",type:"qcm",question:"'We are going to the restaurant' in French:",questionFr:"Traduisez : 'Nous allons au restaurant.'",options:["Nous allons au restaurant.","Nous allons à restaurant.","Nous allons le restaurant.","Nous sommes restaurant."],optionsEn:["We are going to the restaurant.","We go to restaurant (missing article)","We go the restaurant","We are restaurant"],correct:"Nous allons au restaurant.",correctEn:"We are going to the restaurant.",explanation:"Au = à + le.",explanationFr:"Au = à + le."},
    {id:"17-6",type:"qcm",question:"Which is an example of futur proche?",questionFr:"Lequel est un exemple de futur proche ?",options:["Je vais manger","J'ai mangé","Je mange","Je mangerai"],optionsEn:["I am going to eat","I ate","I eat","I will eat"],correct:"Je vais manger",correctEn:"I am going to eat",explanation:"Futur proche = aller + infinitive.",explanationFr:"Futur proche = aller + infinitif."},
    {id:"17-7",type:"qcm",question:"'I am going to do the shopping' in French:",questionFr:"Traduisez : 'Je vais faire les courses.'",options:["Je vais faire les courses.","Je vais les courses faire.","Je faire les courses.","Je vais les courses."],optionsEn:["I am going to do the shopping.","I go the shopping do (wrong order)","I do the shopping (present)","I go the shopping"],correct:"Je vais faire les courses.",correctEn:"I am going to do the shopping.",explanation:"Aller + faire = going to do.",explanationFr:"Aller + faire = aller faire."},
    {id:"17-8",type:"qcm",question:"'Soon' in French:",questionFr:"Comment dit-on 'bientôt' ?",options:["Bientôt","Vite","Prochain","Après"],optionsEn:["Soon","Quickly","Next","After"],correct:"Bientôt",correctEn:"Soon",explanation:"Bientôt = soon.",explanationFr:"Bientôt = bientôt."},
    {id:"17-9",type:"qcm",question:"'Next month' in French:",questionFr:"Comment dit-on 'le mois prochain' ?",options:["Le mois prochain","Le prochain mois","Mois prochain","Le prochain mois"],optionsEn:["Next month","Next month (adj before noun)","Month next","Next month (duplicate)"],correct:"Le mois prochain",correctEn:"Next month",explanation:"Mois prochain = next month.",explanationFr:"Mois prochain = mois prochain."},
    {id:"17-10",type:"qcm",question:"'They are going to visit us' in French:",questionFr:"Traduisez : 'Ils vont nous rendre visite.'",options:["Ils vont nous rendre visite.","Ils sont nous visiter.","Ils vont nous visit.","Ils allons visiter."],optionsEn:["They are going to visit us.","They are us visit (wrong)","They go us visit (English)","They we go visit (wrong)"],correct:"Ils vont nous rendre visite.",correctEn:"They are going to visit us.",explanation:"Ils vont + infinitive.",explanationFr:"Ils vont + infinitif."}
  ],
  libre: [
    {id:"17-l1",type:"libre",question:"Translate: 'I'm going to clean the house tomorrow.'",questionFr:"Traduisez : 'Je vais nettoyer la maison demain.'",correct:"Je vais nettoyer la maison demain.",correctEn:"I'm going to clean the house tomorrow.",alternatives:[],explanation:"Futur proche with demain.",explanationFr:"Futur proche avec demain."},
    {id:"17-l2",type:"libre",question:"How do you say 'she is going to'?",questionFr:"Comment dit-on 'elle va' ?",correct:"elle va",correctEn:"she is going to",alternatives:[],explanation:"Aller conjugated: elle va.",explanationFr:"Aller conjugué : elle va."},
    {id:"17-l3",type:"libre",question:"Translate: 'Next week I'm going to visit my family.'",questionFr:"Traduisez : 'La semaine prochaine je vais rendre visite à ma famille.'",correct:"La semaine prochaine je vais rendre visite à ma famille.",correctEn:"Next week I'm going to visit my family.",alternatives:["La semaine prochaine je vais voir ma famille."],explanation:"Rendre visite à = to visit (someone).",explanationFr:"Rendre visite à = rendre visite à."},
    {id:"17-l4",type:"libre",question:"Complete: 'Je vais ___ la vaisselle ce soir.'",questionFr:"Complétez : 'Je vais ___ la vaisselle ce soir.'",correct:"faire",correctEn:"do",alternatives:[],explanation:"Faire la vaisselle = do the dishes.",explanationFr:"Faire la vaisselle = faire la vaisselle."},
    {id:"17-l5",type:"libre",question:"Translate: 'This weekend we're going to the market.'",questionFr:"Traduisez : 'Ce week-end nous allons au marché.'",correct:"Ce week-end nous allons au marché.",correctEn:"This weekend we're going to the market.",alternatives:[],explanation:"Au marché = to the market.",explanationFr:"Au marché = au marché."},
    {id:"17-l6",type:"libre",question:"How do you say 'soon'?",questionFr:"Comment dit-on 'bientôt' ?",correct:"bientôt",correctEn:"soon",alternatives:[],explanation:"Bientôt = soon.",explanationFr:"Bientôt = bientôt."},
    {id:"17-l7",type:"libre",question:"Translate: 'I'm going to rest this afternoon.'",questionFr:"Traduisez : 'Je vais me reposer cet après-midi.'",correct:"Je vais me reposer cet après-midi.",correctEn:"I'm going to rest this afternoon.",alternatives:[],explanation:"Se reposer = to rest.",explanationFr:"Se reposer = se reposer."},
    {id:"17-l8",type:"libre",question:"Complete: 'Nous ___ aller au restaurant samedi.'",questionFr:"Complétez : 'Nous ___ aller au restaurant samedi.'",correct:"allons",correctEn:"are going to",alternatives:[],explanation:"Nous allons = we are going.",explanationFr:"Nous allons = nous allons."},
    {id:"17-l9",type:"libre",question:"Translate: 'She's going to call next week.'",questionFr:"Traduisez : 'Elle va téléphoner la semaine prochaine.'",correct:"Elle va téléphoner la semaine prochaine.",correctEn:"She's going to call next week.",alternatives:[],explanation:"Téléphoner = to call.",explanationFr:"Téléphoner = téléphoner."},
    {id:"17-l10",type:"libre",question:"How do you say 'next month'?",questionFr:"Comment dit-on 'le mois prochain' ?",correct:"le mois prochain",correctEn:"next month",alternatives:[],explanation:"Prochain comes after noun.",explanationFr:"Prochain vient après le nom."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_17; else window.LESSON_17 = LESSON_17;
