// lesson-12.s
const LESSON_12 = {
  id: 12, title: "My Routine", titleFr: "Ma routine",
  objectiveEn: "Talk about what you did today using passé composé", objectiveFr: "Parler de ce que vous avez fait aujourd'hui en utilisant le passé composé",
  hintEn: "Passé composé = avoir/être + past participle. Most verbs use avoir!", hintFr: "Passé composé = avoir/être + participe passé. La plupart des verbes utilisent avoir !",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"12-1",type:"qcm",question:"'I cleaned the house' in French:",questionFr:"Traduisez : 'J'ai nettoyé la maison.'",options:["J'ai nettoyé la maison.","Je suis nettoyé.","J'ai nettoyer.","Je nettoyais."],optionsEn:["I cleaned the house.","I am cleaned.","I have clean (inf).","I was cleaning."],correct:"J'ai nettoyé la maison.",correctEn:"I cleaned the house.",explanation:"Passé composé with avoir.",explanationFr:"Passé composé avec avoir."},
    {id:"12-2",type:"qcm",question:"'This morning' in French:",questionFr:"Comment dit-on 'ce matin' ?",options:["Ce matin","Cet matin","Cette matin","Ce matinée"],optionsEn:["This morning","This morning (wrong)","This morning (wrong)","This morning (fem wrong)"],correct:"Ce matin",correctEn:"This morning",explanation:"Ce matin = this morning.",explanationFr:"Ce matin = ce matin."},
    {id:"12-3",type:"qcm",question:"Past participle of FAIRE:",questionFr:"Participe passé de FAIRE :",options:["fait","fais","faite","faire"],optionsEn:["done/made","do (present)","done (fem)","to do/make"],correct:"fait",correctEn:"done/made",explanation:"Faire → fait.",explanationFr:"Faire → fait."},
    {id:"12-4",type:"qcm",question:"'I watered the garden' in French:",questionFr:"Traduisez : 'J'ai arrosé le jardin.'",options:["J'ai arrosé le jardin.","Je suis arrosé.","J'ai arroser.","J'arrosais."],optionsEn:["I watered the garden.","I am watered.","I have water (inf).","I was watering."],correct:"J'ai arrosé le jardin.",correctEn:"I watered the garden.",explanation:"Arroser → arrosé.",explanationFr:"Arroser → arrosé."},
    {id:"12-5",type:"qcm",question:"'This afternoon' in French:",questionFr:"Comment dit-on 'cet après-midi' ?",options:["Cet après-midi","Ce après-midi","Cette après-midi","L'après-midi"],optionsEn:["This afternoon","This afternoon (wrong)","This afternoon (wrong)","The afternoon"],correct:"Cet après-midi",correctEn:"This afternoon",explanation:"Cet because après-midi starts with vowel.",explanationFr:"Cet car après-midi commence par une voyelle."},
    {id:"12-6",type:"qcm",question:"'I did the shopping' in French:",questionFr:"Traduisez : 'J'ai fait les courses.'",options:["J'ai fait les courses.","Je suis fait les courses.","J'ai faites les courses.","Je faisais courses."],optionsEn:["I did the shopping.","I am done the shopping.","I have done (fem) the shopping.","I was doing shopping."],correct:"J'ai fait les courses.",correctEn:"I did the shopping.",explanation:"Faire → fait (invariable with avoir).",explanationFr:"Faire → fait (invariable avec avoir)."},
    {id:"12-7",type:"qcm",question:"'Yesterday' in French:",questionFr:"Comment dit-on 'hier' ?",options:["Hier","Demain","Ce matin","Ce soir"],optionsEn:["Yesterday","Tomorrow","This morning","This evening"],correct:"Hier",correctEn:"Yesterday",explanation:"Hier = yesterday.",explanationFr:"Hier = hier."},
    {id:"12-8",type:"qcm",question:"'I tidied up' in French:",questionFr:"Traduisez : 'J'ai rangé.'",options:["J'ai rangé.","Je suis rangé.","J'ai ranger.","Je rangeais."],optionsEn:["I tidied up.","I am tidied.","I have tidy (inf).","I was tidying."],correct:"J'ai rangé.",correctEn:"I tidied up.",explanation:"Ranger → rangé.",explanationFr:"Ranger → rangé."},
    {id:"12-9",type:"qcm",question:"'I just finished' in French:",questionFr:"Traduisez : 'Je viens de finir.'",options:["Je viens de finir.","J'ai venu finir.","Je suis de finir.","J'ai juste fini."],optionsEn:["I just finished.","I came finish.","I am of finish.","I just have finished."],correct:"Je viens de finir.",correctEn:"I just finished.",explanation:"Venir de + infinitive = just did.",explanationFr:"Venir de + infinitif = venir de faire."},
    {id:"12-10",type:"qcm",question:"'This evening' in French:",questionFr:"Comment dit-on 'ce soir' ?",options:["Ce soir","Ce soirée","Cette soir","Le soir"],optionsEn:["This evening","This evening (wrong)","This evening (wrong)","The evening"],correct:"Ce soir",correctEn:"This evening",explanation:"Ce soir = this evening.",explanationFr:"Ce soir = ce soir."}
  ],
  libre: [
    {id:"12-l1",type:"libre",question:"Past participle of 'nettoyer' (to clean):",questionFr:"Participe passé de 'nettoyer' :",correct:"nettoyé",correctEn:"cleaned",alternatives:[],explanation:"-er verbs: add -é.",explanationFr:"Verbes en -er : ajouter -é."},
    {id:"12-l2",type:"libre",question:"Translate: 'This morning I did the shopping.'",questionFr:"Traduisez : 'Ce matin j'ai fait les courses.'",correct:"Ce matin j'ai fait les courses.",correctEn:"This morning I did the shopping.",alternatives:[],explanation:"J'ai fait = I did.",explanationFr:"J'ai fait = j'ai fait."},
    {id:"12-l3",type:"libre",question:"How do you say 'I watered the garden'?",questionFr:"Comment dit-on 'J'ai arrosé le jardin' ?",correct:"J'ai arrosé le jardin.",correctEn:"I watered the garden.",alternatives:[],explanation:"Arroser → arrosé.",explanationFr:"Arroser → arrosé."},
    {id:"12-l4",type:"libre",question:"Translate: 'This evening I'm going to rest.'",questionFr:"Traduisez : 'Ce soir je vais me reposer.'",correct:"Ce soir je vais me reposer.",correctEn:"This evening I'm going to rest.",alternatives:[],explanation:"Je vais + infinitive = near future.",explanationFr:"Je vais + infinitif = futur proche."},
    {id:"12-l5",type:"libre",question:"Complete: 'J'ai ___ la vaisselle ce matin.'",questionFr:"Complétez : 'J'ai ___ la vaisselle ce matin.'",correct:"fait",correctEn:"done",alternatives:[],explanation:"Faire la vaisselle = do the dishes.",explanationFr:"Faire la vaisselle = faire la vaisselle."},
    {id:"12-l6",type:"libre",question:"How do you say 'I just arrived'?",questionFr:"Comment dit-on 'Je viens d'arriver' ?",correct:"Je viens d'arriver.",correctEn:"I just arrived.",alternatives:[],explanation:"Venir de = just did.",explanationFr:"Venir de = venir de."},
    {id:"12-l7",type:"libre",question:"Translate: 'Yesterday I cleaned the whole house.'",questionFr:"Traduisez : 'Hier j'ai nettoyé toute la maison.'",correct:"Hier j'ai nettoyé toute la maison.",correctEn:"Yesterday I cleaned the whole house.",alternatives:[],explanation:"Toute la maison = the whole house.",explanationFr:"Toute la maison = toute la maison."},
    {id:"12-l8",type:"libre",question:"What does 'ce soir' mean?",questionFr:"Que signifie 'ce soir' ?",correct:"this evening",correctEn:"this evening",alternatives:["tonight"],explanation:"Ce soir = this evening / tonight.",explanationFr:"Ce soir = ce soir / cette nuit."},
    {id:"12-l9",type:"libre",question:"Complete: 'J'ai ___ le jardin ce matin.'",questionFr:"Complétez : 'J'ai ___ le jardin ce matin.'",correct:"arrosé",correctEn:"watered",alternatives:[],explanation:"Arroser → arrosé.",explanationFr:"Arroser → arrosé."},
    {id:"12-l10",type:"libre",question:"Translate: 'I need to tidy up tomorrow.'",questionFr:"Traduisez : 'Je dois ranger demain.'",correct:"Je dois ranger demain.",correctEn:"I need to tidy up tomorrow.",alternatives:[],explanation:"Ranger = to tidy up.",explanationFr:"Ranger = ranger."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_12; else window.LESSON_12 = LESSON_12;
