// lesson-20.js
const LESSON_20 = {
  id: 20, title: "Living French", titleFr: "Le français vivant",
  objectiveEn: "Understand and use everyday French expressions naturally", objectiveFr: "Comprendre et utiliser naturellement les expressions françaises du quotidien",
  hintEn: "Pas terrible is a TRAP — it means NOT GREAT, not 'not terrible'!", hintFr: "Pas terrible est un PIÈGE — ça signifie PAS TOP, pas 'pas terrible' !",
  vocabulary: [],
  contentHtml: `...`,
  qcm: [
    {id:"20-1",type:"qcm",question:"'Ça marche !' means:",questionFr:"Que signifie 'Ça marche !' ?",options:["OK! / That works!","It walks!","Let's go!","No problem!"],optionsEn:["OK! / That works!","It walks!","Let's go!","No problem!"],correct:"OK! / That works!",correctEn:"OK! / That works!",explanation:"Ça marche = OK / it works.",explanationFr:"Ça marche = OK / ça fonctionne."},
    {id:"20-2",type:"qcm",question:"What does 'Bof...' express?",questionFr:"Que signifie 'Bof...' ?",options:["Indifference / meh / so-so","Happiness","Surprise","Agreement"],optionsEn:["Indifference / meh / so-so","Happiness","Surprise","Agreement"],correct:"Indifference / meh / so-so",correctEn:"Indifference / meh / so-so",explanation:"Bof = meh / so-so.",explanationFr:"Bof = bof / pas top."},
    {id:"20-3",type:"qcm",question:"'Nickel !' in spoken French means:",questionFr:"'Nickel !' en français familier signifie :",options:["Perfect! / Spotless!","A coin","Not great","It's OK"],optionsEn:["Perfect! / Spotless!","A coin","Not great","It's OK"],correct:"Perfect! / Spotless!",correctEn:"Perfect! / Spotless!",explanation:"Nickel = perfect.",explanationFr:"Nickel = parfait."},
    {id:"20-4",type:"qcm",question:"WARNING: 'Pas terrible' really means:",questionFr:"ATTENTION : 'Pas terrible' signifie réellement :",options:["Not great / disappointing","Not terrible","Quite good","Rather good"],optionsEn:["Not great / disappointing","Not terrible","Quite good","Rather good"],correct:"Not great / disappointing",correctEn:"Not great / disappointing",explanation:"Pas terrible = not great (trap).",explanationFr:"Pas terrible = pas top (piège)."},
    {id:"20-5",type:"qcm",question:"'En fait' translates as:",questionFr:"'En fait' se traduit par :",options:["Actually / in fact","In effect","The fact is","Indeed"],optionsEn:["Actually / in fact","In effect","The fact is","Indeed"],correct:"Actually / in fact",correctEn:"Actually / in fact",explanation:"En fait = actually.",explanationFr:"En fait = en fait."},
    {id:"20-6",type:"qcm",question:"'Du coup' means:",questionFr:"'Du coup' signifie :",options:["So / therefore / as a result","From the start","All of a sudden","At once"],optionsEn:["So / therefore / as a result","From the start","All of a sudden","At once"],correct:"So / therefore / as a result",correctEn:"So / therefore / as a result",explanation:"Du coup = so / therefore.",explanationFr:"Du coup = du coup."},
    {id:"20-7",type:"qcm",question:"'Ça dépend.' means:",questionFr:"'Ça dépend.' signifie :",options:["It depends.","That's expensive.","It doesn't matter.","So much the better."],optionsEn:["It depends.","That's expensive.","It doesn't matter.","So much the better."],correct:"It depends.",correctEn:"It depends.",explanation:"Ça dépend = it depends.",explanationFr:"Ça dépend = ça dépend."},
    {id:"20-8",type:"qcm",question:"'Franchement' means:",questionFr:"'Franchement' signifie :",options:["Frankly / honestly","In French","Freely","Actually"],optionsEn:["Frankly / honestly","In French","Freely","Actually"],correct:"Frankly / honestly",correctEn:"Frankly / honestly",explanation:"Franchement = frankly.",explanationFr:"Franchement = franchement."},
    {id:"20-9",type:"qcm",question:"'Quand même' is best translated as:",questionFr:"'Quand même' se traduit le mieux par :",options:["Still / anyway / come on!","When even","Same time","Just the same"],optionsEn:["Still / anyway / come on!","When even","Same time","Just the same"],correct:"Still / anyway / come on!",correctEn:"Still / anyway / come on!",explanation:"Quand même = still / anyway.",explanationFr:"Quand même = quand même."},
    {id:"20-10",type:"qcm",question:"'Comme d'habitude' means:",questionFr:"'Comme d'habitude' signifie :",options:["As usual","As a habit","Like always","Just in case"],optionsEn:["As usual","As a habit","Like always","Just in case"],correct:"As usual",correctEn:"As usual",explanation:"Comme d'habitude = as usual.",explanationFr:"Comme d'habitude = comme d'habitude."}
  ],
  libre: [
    {id:"20-l1",type:"libre",question:"How do French people say 'OK' informally?",questionFr:"Comment les Français disent-ils 'OK' informellement ?",correct:"Ça marche !",correctEn:"Ça marche!",alternatives:["D'accord","OK"],explanation:"Ça marche is informal OK.",explanationFr:"Ça marche = OK informel."},
    {id:"20-l2",type:"libre",question:"How do you say 'actually' in French?",questionFr:"Comment dit-on 'en fait' ?",correct:"en fait",correctEn:"actually",alternatives:[],explanation:"En fait = actually.",explanationFr:"En fait = en fait."},
    {id:"20-l3",type:"libre",question:"Translate: 'So I went to the market.'",questionFr:"Traduisez : 'Du coup je suis allé au marché.'",correct:"Du coup je suis allé au marché.",correctEn:"So I went to the market.",alternatives:[],explanation:"Du coup = so.",explanationFr:"Du coup = du coup."},
    {id:"20-l4",type:"libre",question:"How do you say 'frankly'?",questionFr:"Comment dit-on 'franchement' ?",correct:"franchement",correctEn:"frankly",alternatives:[],explanation:"Franchement = frankly.",explanationFr:"Franchement = franchement."},
    {id:"20-l5",type:"libre",question:"What does 'Bof' express?",questionFr:"Qu'exprime 'Bof' ?",correct:"indifference",correctEn:"indifference",alternatives:["meh","so-so","not really"],explanation:"Bof = indifference.",explanationFr:"Bof = indifférence."},
    {id:"20-l6",type:"libre",question:"How do you say 'it depends'?",questionFr:"Comment dit-on 'ça dépend' ?",correct:"ça dépend",correctEn:"it depends",alternatives:[],explanation:"Ça dépend = it depends.",explanationFr:"Ça dépend = ça dépend."},
    {id:"20-l7",type:"libre",question:"Translate: 'He's late, as usual.'",questionFr:"Traduisez : 'Il est en retard, comme d'habitude.'",correct:"Il est en retard, comme d'habitude.",correctEn:"He's late, as usual.",alternatives:[],explanation:"Comme d'habitude = as usual.",explanationFr:"Comme d'habitude = comme d'habitude."},
    {id:"20-l8",type:"libre",question:"What is the REAL meaning of 'pas terrible'?",questionFr:"Quel est le VRAI sens de 'pas terrible' ?",correct:"not great",correctEn:"not great",alternatives:["not good","disappointing","mediocre"],explanation:"Pas terrible = not great (trap).",explanationFr:"Pas terrible = pas top (piège)."},
    {id:"20-l9",type:"libre",question:"How do you say 'still / anyway'?",questionFr:"Comment dit-on 'quand même' ?",correct:"quand même",correctEn:"still / anyway",alternatives:[],explanation:"Quand même = still/anyway.",explanationFr:"Quand même = quand même."},
    {id:"20-l10",type:"libre",question:"Translate: 'It works, perfect!'",questionFr:"Traduisez : 'Ça marche, nickel !'",correct:"Ça marche, nickel !",correctEn:"It works, perfect!",alternatives:[],explanation:"Nickel = perfect.",explanationFr:"Nickel = parfait."}
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = LESSON_20; else window.LESSON_20 = LESSON_20;
